/**
 * Grand Design Imagine lot-record fills from the RV Country scrape
 * dated 2026-09-25 (public/inventory/own-lot-latest.json).
 *
 * Pilot slice: Imagine, Imagine AIM, and Imagine XLS only.
 * One row per year + model + floorplan. Not an OEM brochure pin.
 * Unflagged numbers fill empty catalog cells. overridesCatalog marks a
 * lot value that replaces the catalog / OEM / brochure number for that
 * exact coach and field. sourceNote lists every agreeing unit, and for
 * an override both the lot value and the catalog value it replaced.
 */

import type { LotCatalogSeedRow } from "./lotCatalogSeed.ts";

export type GrandDesignLotSeedRow = LotCatalogSeedRow & {
  sourceNote: string;
};

export const GRAND_DESIGN_LOT_SEED: GrandDesignLotSeedRow[] = [
  // Imagine
  {
    year: 2019,
    make: "Grand Design",
    model: "Imagine",
    trim: "2800BH",
    title: "2019 Grand Design Imagine 2800BH",
    stock_number: "47686A",
    gvwr: 7995,
    dry_weight: 6195,
    hitch_weight: 604,
    vehicle_body_length: 32,
    propane_lbs: 40,
    total_gray_water_tank_capacity: 76,
    max_sleeping_count: 10,
    number_of_slideouts: 2,
    source: "RV Country lot unit record",
    overridesCatalog: {
      total_gray_water_tank_capacity: true,
      max_sleeping_count: true,
      number_of_slideouts: true,
    },
    sourceNote:
      "public/inventory/own-lot-latest.json · scraped 2026-09-25 · GVWR, UVW/dry, Hitch/pin, Length (ft), Propane (lb), Gray (gal), Sleeps, Slides · id 216875 / stock 47686A · Overrides catalog: Gray 76 gal replaces 39 gal (rvData series seed); Sleeps 10 replaces 8 (rvData series seed); Slides 2 replaces 1 (rvData series seed)",
  },
  {
    year: 2022,
    make: "Grand Design",
    model: "Imagine",
    trim: "3100RD",
    title: "2022 Grand Design Imagine 3100RD",
    stock_number: "42875A",
    gvwr: 9495,
    dry_weight: 7778,
    hitch_weight: 791,
    payload: 1717,
    propane_lbs: 40,
    total_gray_water_tank_capacity: 90,
    total_black_water_tank_capacity: 45,
    max_sleeping_count: 6,
    number_of_slideouts: 2,
    source: "RV Country lot unit record",
    overridesCatalog: {
      total_gray_water_tank_capacity: true,
      total_black_water_tank_capacity: true,
      max_sleeping_count: true,
      number_of_slideouts: true,
    },
    sourceNote:
      "public/inventory/own-lot-latest.json · scraped 2026-09-25 · GVWR, UVW/dry, Hitch/pin, CCC/payload, Propane (lb), Gray (gal), Black (gal), Sleeps, Slides · id 175476 / stock 42875A · Overrides catalog: Gray 90 gal replaces 39 gal (rvData series seed); Black 45 gal replaces 39 gal (rvData series seed); Sleeps 6 replaces 8 (rvData series seed); Slides 2 replaces 1 (rvData series seed)",
  },
  {
    year: 2025,
    make: "Grand Design",
    model: "Imagine",
    trim: "2600RB",
    title: "2025 Grand Design Imagine 2600RB",
    stock_number: "46147A",
    gvwr: 7850,
    dry_weight: 5795,
    hitch_weight: 594,
    vehicle_body_length: 29.67,
    propane_lbs: 40,
    total_gray_water_tank_capacity: 82,
    total_black_water_tank_capacity: 45,
    max_sleeping_count: 6,
    source: "RV Country lot unit record",
    overridesCatalog: {
      total_gray_water_tank_capacity: true,
      total_black_water_tank_capacity: true,
      max_sleeping_count: true,
    },
    sourceNote:
      "public/inventory/own-lot-latest.json · scraped 2026-09-25 · GVWR, UVW/dry, Hitch/pin, Length (ft), Propane (lb), Gray (gal), Black (gal), Sleeps · id 216327 / stock 46147A · Overrides catalog: Gray 82 gal replaces 39 gal (rvData series seed); Black 45 gal replaces 39 gal (rvData series seed); Sleeps 6 replaces 8 (rvData series seed)",
  },
  {
    year: 2025,
    make: "Grand Design",
    model: "Imagine",
    trim: "2670MK",
    title: "2025 Grand Design Imagine 2670MK",
    stock_number: "45069",
    gvwr: 8495,
    dry_weight: 6845,
    hitch_weight: 690,
    total_fresh_water_tank_capacity: 52,
    max_sleeping_count: 6,
    number_of_slideouts: 2,
    source: "RV Country lot unit record",
    overridesCatalog: {
      gvwr: true,
      dry_weight: true,
      hitch_weight: true,
      total_fresh_water_tank_capacity: true,
      max_sleeping_count: true,
      number_of_slideouts: true,
    },
    sourceNote:
      "public/inventory/own-lot-latest.json · scraped 2026-09-25 · GVWR, UVW/dry, Hitch/pin, Fresh (gal), Sleeps, Slides · id 37347 / stock 45069 · Overrides catalog: GVWR 8,495 lb replaces 8,995 lb (OEM: Grand Design Imagine series brochure (2670MK class)); UVW/dry 6,845 lb replaces 6,895 lb (OEM: Grand Design Imagine series brochure (2670MK class)); Hitch/pin 690 lb replaces 720 lb (OEM: Grand Design Imagine series brochure (2670MK class)); Fresh 52 gal replaces 45 gal (OEM: Grand Design Imagine series brochure (2670MK class)); Sleeps 6 replaces 8 (rvData series seed); Slides 2 replaces 1 (rvData series seed)",
  },
  {
    year: 2026,
    make: "Grand Design",
    model: "Imagine",
    trim: "2300MK",
    title: "2026 Grand Design Imagine 2300MK",
    stock_number: "45458 / 45459",
    gvwr: 7850,
    dry_weight: 6012,
    hitch_weight: 641,
    payload: 1838,
    vehicle_body_length: 26.5,
    propane_lbs: 40,
    total_fresh_water_tank_capacity: 45,
    total_gray_water_tank_capacity: 82,
    total_black_water_tank_capacity: 45,
    max_sleeping_count: 4,
    source: "RV Country lot unit record",
    overridesCatalog: {
      total_fresh_water_tank_capacity: true,
      total_gray_water_tank_capacity: true,
      total_black_water_tank_capacity: true,
      max_sleeping_count: true,
    },
    sourceNote:
      "public/inventory/own-lot-latest.json · scraped 2026-09-25 · GVWR, UVW/dry, Hitch/pin, CCC/payload, Length (ft), Propane (lb), Fresh (gal), Gray (gal), Black (gal), Sleeps · id 38148 / stock 45458; id 38153 / stock 45459 · Overrides catalog: Fresh 45 gal replaces 52 gal (rvData series seed); Gray 82 gal replaces 39 gal (rvData series seed); Black 45 gal replaces 39 gal (rvData series seed); Sleeps 4 replaces 8 (rvData series seed)",
  },
  {
    year: 2026,
    make: "Grand Design",
    model: "Imagine",
    trim: "2470BH",
    title: "2026 Grand Design Imagine 2470BH",
    stock_number: "46314",
    gvwr: 7850,
    dry_weight: 6406,
    hitch_weight: 659,
    payload: 1444,
    propane_lbs: 40,
    total_fresh_water_tank_capacity: 45,
    total_gray_water_tank_capacity: 82,
    total_black_water_tank_capacity: 45,
    source: "RV Country lot unit record",
    overridesCatalog: {
      total_fresh_water_tank_capacity: true,
      total_gray_water_tank_capacity: true,
      total_black_water_tank_capacity: true,
    },
    sourceNote:
      "public/inventory/own-lot-latest.json · scraped 2026-09-25 · GVWR, UVW/dry, Hitch/pin, CCC/payload, Propane (lb), Fresh (gal), Gray (gal), Black (gal) · id 95103 / stock 46314 · Overrides catalog: Fresh 45 gal replaces 52 gal (rvData series seed); Gray 82 gal replaces 39 gal (rvData series seed); Black 45 gal replaces 39 gal (rvData series seed)",
  },
  {
    year: 2026,
    make: "Grand Design",
    model: "Imagine",
    trim: "2500RL",
    title: "2026 Grand Design Imagine 2500RL",
    stock_number: "47322",
    gvwr: 7850,
    dry_weight: 6623,
    hitch_weight: 581,
    max_sleeping_count: 6,
    source: "RV Country lot unit record",
    overridesCatalog: {
      gvwr: true,
      dry_weight: true,
      hitch_weight: true,
      max_sleeping_count: true,
    },
    sourceNote:
      "public/inventory/own-lot-latest.json · scraped 2026-09-25 · GVWR, UVW/dry, Hitch/pin, Sleeps · id 131708 / stock 47322 · Overrides catalog: GVWR 7,850 lb replaces 7,995 lb (OEM: Grand Design Imagine series brochure (2500RL class)); UVW/dry 6,623 lb replaces 6,495 lb (OEM: Grand Design Imagine series brochure (2500RL class)); Hitch/pin 581 lb replaces 680 lb (OEM: Grand Design Imagine series brochure (2500RL class)); Sleeps 6 replaces 8 (rvData series seed)",
  },
  {
    year: 2026,
    make: "Grand Design",
    model: "Imagine",
    trim: "2600RB",
    title: "2026 Grand Design Imagine 2600RB",
    stock_number: "47437 / 47449",
    gvwr: 7850,
    dry_weight: 6533,
    hitch_weight: 594,
    vehicle_body_length: 29.67,
    propane_lbs: 40,
    total_fresh_water_tank_capacity: 45,
    total_gray_water_tank_capacity: 82,
    total_black_water_tank_capacity: 45,
    max_sleeping_count: 6,
    source: "RV Country lot unit record",
    overridesCatalog: {
      total_fresh_water_tank_capacity: true,
      total_gray_water_tank_capacity: true,
      total_black_water_tank_capacity: true,
      max_sleeping_count: true,
    },
    sourceNote:
      "public/inventory/own-lot-latest.json · scraped 2026-09-25 · GVWR, UVW/dry, Hitch/pin, Length (ft), Propane (lb), Fresh (gal), Gray (gal), Black (gal), Sleeps · id 150540 / stock 47437; id 150552 / stock 47449 · Overrides catalog: Fresh 45 gal replaces 52 gal (rvData series seed); Gray 82 gal replaces 39 gal (rvData series seed); Black 45 gal replaces 39 gal (rvData series seed); Sleeps 6 replaces 8 (rvData series seed)",
  },
  {
    year: 2026,
    make: "Grand Design",
    model: "Imagine",
    trim: "2670MK",
    title: "2026 Grand Design Imagine 2670MK",
    stock_number: "45455 / 45634 / 46583",
    hitch_weight: 690,
    vehicle_body_length: 32.25,
    max_sleeping_count: 6,
    number_of_slideouts: 2,
    source: "RV Country lot unit record",
    overridesCatalog: {
      hitch_weight: true,
      vehicle_body_length: true,
      max_sleeping_count: true,
      number_of_slideouts: true,
    },
    sourceNote:
      "public/inventory/own-lot-latest.json · scraped 2026-09-25 · Hitch/pin, Length (ft), Sleeps, Slides · id 38135 / stock 45455; id 38192 / stock 45634; id 109367 / stock 46583 · Overrides catalog: Hitch/pin 690 lb replaces 720 lb (OEM: Grand Design Imagine series brochure (2670MK class)); Length 32.25 ft replaces 32 ft (OEM: Grand Design Imagine series brochure (2670MK class)); Sleeps 6 replaces 8 (rvData series seed); Slides 2 replaces 1 (rvData series seed)",
  },
  {
    year: 2026,
    make: "Grand Design",
    model: "Imagine",
    trim: "2700BS",
    title: "2026 Grand Design Imagine 2700BS",
    stock_number: "46146 / 46149 / 47183",
    gvwr: 10195,
    dry_weight: 7180,
    hitch_weight: 760,
    vehicle_body_length: 31.67,
    total_fresh_water_tank_capacity: 45,
    total_gray_water_tank_capacity: 90,
    total_black_water_tank_capacity: 45,
    max_sleeping_count: 2,
    number_of_slideouts: 2,
    source: "RV Country lot unit record",
    overridesCatalog: {
      total_fresh_water_tank_capacity: true,
      total_gray_water_tank_capacity: true,
      total_black_water_tank_capacity: true,
      max_sleeping_count: true,
      number_of_slideouts: true,
    },
    sourceNote:
      "public/inventory/own-lot-latest.json · scraped 2026-09-25 · GVWR, UVW/dry, Hitch/pin, Length (ft), Fresh (gal), Gray (gal), Black (gal), Sleeps, Slides · id 90258 / stock 46146; id 90280 / stock 46149; id 128526 / stock 47183 · Overrides catalog: Fresh 45 gal replaces 52 gal (rvData series seed); Gray 90 gal replaces 39 gal (rvData series seed); Black 45 gal replaces 39 gal (rvData series seed); Sleeps 2 replaces 8 (rvData series seed); Slides 2 replaces 1 (rvData series seed)",
  },
  {
    year: 2026,
    make: "Grand Design",
    model: "Imagine",
    trim: "2800BH",
    title: "2026 Grand Design Imagine 2800BH",
    stock_number: "45788",
    gvwr: 8495,
    dry_weight: 6386,
    hitch_weight: 604,
    total_fresh_water_tank_capacity: 52,
    max_sleeping_count: 10,
    source: "RV Country lot unit record",
    overridesCatalog: {
      gvwr: true,
      dry_weight: true,
      hitch_weight: true,
      total_fresh_water_tank_capacity: true,
      max_sleeping_count: true,
    },
    sourceNote:
      "public/inventory/own-lot-latest.json · scraped 2026-09-25 · GVWR, UVW/dry, Hitch/pin, Fresh (gal), Sleeps · id 38275 / stock 45788 · Overrides catalog: GVWR 8,495 lb replaces 10,195 lb (OEM: Grand Design Imagine 2800BH product page); UVW/dry 6,386 lb replaces 7,185 lb (OEM: Grand Design Imagine 2800BH product page); Hitch/pin 604 lb replaces 746 lb (OEM: Grand Design Imagine 2800BH product page); Fresh 52 gal replaces 45 gal (OEM: Grand Design Imagine 2800BH product page); Sleeps 10 replaces 8 (rvData series seed)",
  },
  {
    year: 2026,
    make: "Grand Design",
    model: "Imagine",
    trim: "2810BH",
    title: "2026 Grand Design Imagine 2810BH",
    stock_number: "47184 / 47552",
    gvwr: 10195,
    dry_weight: 7510,
    hitch_weight: 771,
    vehicle_body_length: 32.25,
    total_fresh_water_tank_capacity: 45,
    total_gray_water_tank_capacity: 82,
    total_black_water_tank_capacity: 45,
    max_sleeping_count: 5,
    number_of_slideouts: 2,
    source: "RV Country lot unit record",
    overridesCatalog: {
      total_fresh_water_tank_capacity: true,
      total_gray_water_tank_capacity: true,
      total_black_water_tank_capacity: true,
      max_sleeping_count: true,
      number_of_slideouts: true,
    },
    sourceNote:
      "public/inventory/own-lot-latest.json · scraped 2026-09-25 · GVWR, UVW/dry, Hitch/pin, Length (ft), Fresh (gal), Gray (gal), Black (gal), Sleeps, Slides · id 128524 / stock 47184; id 177852 / stock 47552 · Overrides catalog: Fresh 45 gal replaces 52 gal (rvData series seed); Gray 82 gal replaces 39 gal (rvData series seed); Black 45 gal replaces 39 gal (rvData series seed); Sleeps 5 replaces 8 (rvData series seed); Slides 2 replaces 1 (rvData series seed)",
  },
  {
    year: 2026,
    make: "Grand Design",
    model: "Imagine",
    trim: "2970RL",
    title: "2026 Grand Design Imagine 2970RL",
    stock_number: "46558 / 47261",
    gvwr: 10195,
    dry_weight: 7810,
    hitch_weight: 751,
    vehicle_body_length: 34.17,
    propane_lbs: 40,
    total_fresh_water_tank_capacity: 45,
    total_gray_water_tank_capacity: 90,
    total_black_water_tank_capacity: 45,
    max_sleeping_count: 6,
    number_of_slideouts: 2,
    source: "RV Country lot unit record",
    overridesCatalog: {
      total_fresh_water_tank_capacity: true,
      total_gray_water_tank_capacity: true,
      total_black_water_tank_capacity: true,
      max_sleeping_count: true,
      number_of_slideouts: true,
    },
    sourceNote:
      "public/inventory/own-lot-latest.json · scraped 2026-09-25 · GVWR, UVW/dry, Hitch/pin, Length (ft), Propane (lb), Fresh (gal), Gray (gal), Black (gal), Sleeps, Slides · id 99332 / stock 46558; id 130326 / stock 47261 · Overrides catalog: Fresh 45 gal replaces 52 gal (rvData series seed); Gray 90 gal replaces 39 gal (rvData series seed); Black 45 gal replaces 39 gal (rvData series seed); Sleeps 6 replaces 8 (rvData series seed); Slides 2 replaces 1 (rvData series seed)",
  },
  {
    year: 2026,
    make: "Grand Design",
    model: "Imagine",
    trim: "3100RD",
    title: "2026 Grand Design Imagine 3100RD",
    stock_number: "46585",
    gvwr: 10195,
    dry_weight: 8076,
    hitch_weight: 791,
    propane_lbs: 40,
    total_fresh_water_tank_capacity: 45,
    total_gray_water_tank_capacity: 90,
    total_black_water_tank_capacity: 45,
    max_sleeping_count: 6,
    number_of_slideouts: 2,
    source: "RV Country lot unit record",
    overridesCatalog: {
      total_fresh_water_tank_capacity: true,
      total_gray_water_tank_capacity: true,
      total_black_water_tank_capacity: true,
      max_sleeping_count: true,
      number_of_slideouts: true,
    },
    sourceNote:
      "public/inventory/own-lot-latest.json · scraped 2026-09-25 · GVWR, UVW/dry, Hitch/pin, Propane (lb), Fresh (gal), Gray (gal), Black (gal), Sleeps, Slides · id 99752 / stock 46585 · Overrides catalog: Fresh 45 gal replaces 52 gal (rvData series seed); Gray 90 gal replaces 39 gal (rvData series seed); Black 45 gal replaces 39 gal (rvData series seed); Sleeps 6 replaces 8 (rvData series seed); Slides 2 replaces 1 (rvData series seed)",
  },
  {
    year: 2027,
    make: "Grand Design",
    model: "Imagine",
    trim: "2600RB",
    title: "2027 Grand Design Imagine 2600RB",
    stock_number: "47563",
    gvwr: 7850,
    dry_weight: 6533,
    hitch_weight: 594,
    vehicle_body_length: 29.67,
    propane_lbs: 40,
    total_fresh_water_tank_capacity: 45,
    total_gray_water_tank_capacity: 82,
    total_black_water_tank_capacity: 45,
    max_sleeping_count: 6,
    source: "RV Country lot unit record",
    overridesCatalog: {
      total_fresh_water_tank_capacity: true,
      total_gray_water_tank_capacity: true,
      total_black_water_tank_capacity: true,
      max_sleeping_count: true,
    },
    sourceNote:
      "public/inventory/own-lot-latest.json · scraped 2026-09-25 · GVWR, UVW/dry, Hitch/pin, Length (ft), Propane (lb), Fresh (gal), Gray (gal), Black (gal), Sleeps · id 178487 / stock 47563 · Overrides catalog: Fresh 45 gal replaces 52 gal (rvData series seed); Gray 82 gal replaces 39 gal (rvData series seed); Black 45 gal replaces 39 gal (rvData series seed); Sleeps 6 replaces 8 (rvData series seed)",
  },
  // Imagine AIM
  {
    year: 2026,
    make: "Grand Design",
    model: "Imagine AIM",
    trim: "15RBA",
    title: "2026 Grand Design Imagine AIM 15RBA",
    stock_number: "47418",
    gvwr: 4795,
    dry_weight: 3547,
    hitch_weight: 392,
    max_sleeping_count: 3,
    source: "RV Country lot unit record",
    overridesCatalog: { max_sleeping_count: true },
    sourceNote:
      "public/inventory/own-lot-latest.json · scraped 2026-09-25 · GVWR, UVW/dry, Hitch/pin, Sleeps · id 150507 / stock 47418 · Overrides catalog: Sleeps 3 replaces 4 (rvData series seed)",
  },
  {
    year: 2026,
    make: "Grand Design",
    model: "Imagine AIM",
    trim: "16MLA",
    title: "2026 Grand Design Imagine AIM 16MLA",
    stock_number: "47072",
    gvwr: 4795,
    dry_weight: 3813,
    hitch_weight: 432,
    max_sleeping_count: 3,
    number_of_slideouts: 1,
    source: "RV Country lot unit record",
    overridesCatalog: { max_sleeping_count: true, number_of_slideouts: true },
    sourceNote:
      "public/inventory/own-lot-latest.json · scraped 2026-09-25 · GVWR, UVW/dry, Hitch/pin, Sleeps, Slides · id 120641 / stock 47072 · Overrides catalog: Sleeps 3 replaces 4 (rvData series seed); Slides 1 replaces 0 (rvData series seed)",
  },
  {
    year: 2026,
    make: "Grand Design",
    model: "Imagine AIM",
    trim: "19MLA",
    title: "2026 Grand Design Imagine AIM 19MLA",
    stock_number: "47073 / 47419 / 47434",
    gvwr: 6395,
    dry_weight: 4361,
    hitch_weight: 478,
    vehicle_body_length: 22,
    max_sleeping_count: 2,
    source: "RV Country lot unit record",
    overridesCatalog: { max_sleeping_count: true },
    sourceNote:
      "public/inventory/own-lot-latest.json · scraped 2026-09-25 · GVWR, UVW/dry, Hitch/pin, Length (ft), Sleeps · id 120643 / stock 47073; id 150508 / stock 47419; id 150537 / stock 47434 · Overrides catalog: Sleeps 2 replaces 4 (rvData series seed)",
  },
  // Imagine XLS
  {
    year: 2021,
    make: "Grand Design",
    model: "Imagine XLS",
    trim: "21BHE",
    title: "2021 Grand Design Imagine XLS 21BHE",
    stock_number: "UCO9924",
    gvwr: 5995,
    dry_weight: 4698,
    hitch_weight: 456,
    payload: 1297,
    propane_lbs: 40,
    total_fresh_water_tank_capacity: 43,
    total_gray_water_tank_capacity: 45,
    total_black_water_tank_capacity: 37,
    max_sleeping_count: 8,
    source: "RV Country lot unit record",
    overridesCatalog: { max_sleeping_count: true },
    sourceNote:
      "public/inventory/own-lot-latest.json · scraped 2026-09-25 · GVWR, UVW/dry, Hitch/pin, CCC/payload, Propane (lb), Fresh (gal), Gray (gal), Black (gal), Sleeps · id 211095 / stock UCO9924 · Overrides catalog: Sleeps 8 replaces 6 (rvData series seed)",
  },
  {
    year: 2022,
    make: "Grand Design",
    model: "Imagine XLS",
    trim: "22MLE",
    title: "2022 Grand Design Imagine XLS 22MLE",
    stock_number: "47690A1",
    gvwr: 6995,
    dry_weight: 5176,
    hitch_weight: 490,
    payload: 1819,
    propane_lbs: 40,
    total_fresh_water_tank_capacity: 43,
    total_gray_water_tank_capacity: 45,
    total_black_water_tank_capacity: 37,
    max_sleeping_count: 4,
    number_of_slideouts: 1,
    source: "RV Country lot unit record",
    overridesCatalog: { max_sleeping_count: true, number_of_slideouts: true },
    sourceNote:
      "public/inventory/own-lot-latest.json · scraped 2026-09-25 · GVWR, UVW/dry, Hitch/pin, CCC/payload, Propane (lb), Fresh (gal), Gray (gal), Black (gal), Sleeps, Slides · id 218923 / stock 47690A1 · Overrides catalog: Sleeps 4 replaces 6 (rvData series seed); Slides 1 replaces 0 (rvData series seed)",
  },
  {
    year: 2022,
    make: "Grand Design",
    model: "Imagine XLS",
    trim: "22RBE",
    title: "2022 Grand Design Imagine XLS 22RBE",
    stock_number: "47165A",
    gvwr: 6995,
    dry_weight: 5125,
    hitch_weight: 497,
    payload: 1870,
    propane_lbs: 40,
    total_fresh_water_tank_capacity: 43,
    total_gray_water_tank_capacity: 82,
    total_black_water_tank_capacity: 37,
    max_sleeping_count: 4,
    number_of_slideouts: 1,
    source: "RV Country lot unit record",
    overridesCatalog: { max_sleeping_count: true, number_of_slideouts: true },
    sourceNote:
      "public/inventory/own-lot-latest.json · scraped 2026-09-25 · GVWR, UVW/dry, Hitch/pin, CCC/payload, Propane (lb), Fresh (gal), Gray (gal), Black (gal), Sleeps, Slides · id 175425 / stock 47165A · Overrides catalog: Sleeps 4 replaces 6 (rvData series seed); Slides 1 replaces 0 (rvData series seed)",
  },
  {
    year: 2025,
    make: "Grand Design",
    model: "Imagine XLS",
    trim: "17MKE",
    title: "2025 Grand Design Imagine XLS 17MKE",
    stock_number: "45497",
    gvwr: 6395,
    dry_weight: 4674,
    hitch_weight: 480,
    propane_lbs: 40,
    total_fresh_water_tank_capacity: 43,
    total_gray_water_tank_capacity: 45,
    total_black_water_tank_capacity: 37,
    max_sleeping_count: 4,
    number_of_slideouts: 1,
    source: "RV Country lot unit record",
    overridesCatalog: { max_sleeping_count: true, number_of_slideouts: true },
    sourceNote:
      "public/inventory/own-lot-latest.json · scraped 2026-09-25 · GVWR, UVW/dry, Hitch/pin, Propane (lb), Fresh (gal), Gray (gal), Black (gal), Sleeps, Slides · id 37959 / stock 45497 · Overrides catalog: Sleeps 4 replaces 6 (rvData series seed); Slides 1 replaces 0 (rvData series seed)",
  },
  {
    year: 2025,
    make: "Grand Design",
    model: "Imagine XLS",
    trim: "22BHE",
    title: "2025 Grand Design Imagine XLS 22BHE",
    stock_number: "45495",
    gvwr: 6995,
    dry_weight: 5589,
    hitch_weight: 543,
    propane_lbs: 40,
    total_fresh_water_tank_capacity: 43,
    total_gray_water_tank_capacity: 45,
    total_black_water_tank_capacity: 37,
    number_of_slideouts: 2,
    source: "RV Country lot unit record",
    overridesCatalog: { number_of_slideouts: true },
    sourceNote:
      "public/inventory/own-lot-latest.json · scraped 2026-09-25 · GVWR, UVW/dry, Hitch/pin, Propane (lb), Fresh (gal), Gray (gal), Black (gal), Slides · id 37950 / stock 45495 · Overrides catalog: Slides 2 replaces 0 (rvData series seed)",
  },
  {
    year: 2026,
    make: "Grand Design",
    model: "Imagine XLS",
    trim: "17MKE",
    title: "2026 Grand Design Imagine XLS 17MKE",
    stock_number: "47264 / 47448",
    gvwr: 6395,
    hitch_weight: 480,
    vehicle_body_length: 21.92,
    propane_lbs: 40,
    total_fresh_water_tank_capacity: 43,
    total_gray_water_tank_capacity: 45,
    total_black_water_tank_capacity: 37,
    max_sleeping_count: 4,
    number_of_slideouts: 1,
    source: "RV Country lot unit record",
    overridesCatalog: { max_sleeping_count: true, number_of_slideouts: true },
    sourceNote:
      "public/inventory/own-lot-latest.json · scraped 2026-09-25 · GVWR, Hitch/pin, Length (ft), Propane (lb), Fresh (gal), Gray (gal), Black (gal), Sleeps, Slides · id 130329 / stock 47264; id 150551 / stock 47448 · Overrides catalog: Sleeps 4 replaces 6 (rvData series seed); Slides 1 replaces 0 (rvData series seed)",
  },
  {
    year: 2026,
    make: "Grand Design",
    model: "Imagine XLS",
    trim: "21MBE",
    title: "2026 Grand Design Imagine XLS 21MBE",
    stock_number: "46240 / 47435",
    gvwr: 6395,
    dry_weight: 5361,
    hitch_weight: 560,
    vehicle_body_length: 24.92,
    total_fresh_water_tank_capacity: 37,
    total_gray_water_tank_capacity: 45,
    total_black_water_tank_capacity: 37,
    max_sleeping_count: 5,
    number_of_slideouts: 1,
    source: "RV Country lot unit record",
    overridesCatalog: { max_sleeping_count: true, number_of_slideouts: true },
    sourceNote:
      "public/inventory/own-lot-latest.json · scraped 2026-09-25 · GVWR, UVW/dry, Hitch/pin, Length (ft), Fresh (gal), Gray (gal), Black (gal), Sleeps, Slides · id 93163 / stock 46240; id 150538 / stock 47435 · Overrides catalog: Sleeps 5 replaces 6 (rvData series seed); Slides 1 replaces 0 (rvData series seed)",
  },
  {
    year: 2026,
    make: "Grand Design",
    model: "Imagine XLS",
    trim: "22RBE",
    title: "2026 Grand Design Imagine XLS 22RBE",
    stock_number: "46317",
    gvwr: 6995,
    dry_weight: 5379,
    hitch_weight: 497,
    propane_lbs: 40,
    total_fresh_water_tank_capacity: 37,
    total_gray_water_tank_capacity: 82,
    total_black_water_tank_capacity: 37,
    max_sleeping_count: 4,
    number_of_slideouts: 1,
    source: "RV Country lot unit record",
    overridesCatalog: { max_sleeping_count: true, number_of_slideouts: true },
    sourceNote:
      "public/inventory/own-lot-latest.json · scraped 2026-09-25 · GVWR, UVW/dry, Hitch/pin, Propane (lb), Fresh (gal), Gray (gal), Black (gal), Sleeps, Slides · id 95109 / stock 46317 · Overrides catalog: Sleeps 4 replaces 6 (rvData series seed); Slides 1 replaces 0 (rvData series seed)",
  },
  {
    year: 2026,
    make: "Grand Design",
    model: "Imagine XLS",
    trim: "25DBE",
    title: "2026 Grand Design Imagine XLS 25DBE",
    stock_number: "45444",
    gvwr: 7395,
    dry_weight: 6198,
    hitch_weight: 631,
    propane_lbs: 40,
    total_fresh_water_tank_capacity: 37,
    total_gray_water_tank_capacity: 82,
    total_black_water_tank_capacity: 37,
    max_sleeping_count: 10,
    number_of_slideouts: 1,
    source: "RV Country lot unit record",
    overridesCatalog: { max_sleeping_count: true, number_of_slideouts: true },
    sourceNote:
      "public/inventory/own-lot-latest.json · scraped 2026-09-25 · GVWR, UVW/dry, Hitch/pin, Propane (lb), Fresh (gal), Gray (gal), Black (gal), Sleeps, Slides · id 38079 / stock 45444 · Overrides catalog: Sleeps 10 replaces 6 (rvData series seed); Slides 1 replaces 0 (rvData series seed)",
  },
  {
    year: 2026,
    make: "Grand Design",
    model: "Imagine XLS",
    trim: "25RLE",
    title: "2026 Grand Design Imagine XLS 25RLE",
    stock_number: "46454 / 46561 / 47262",
    gvwr: 7995,
    dry_weight: 6034,
    hitch_weight: 595,
    vehicle_body_length: 29.75,
    total_fresh_water_tank_capacity: 37,
    total_gray_water_tank_capacity: 45,
    total_black_water_tank_capacity: 37,
    max_sleeping_count: 3,
    number_of_slideouts: 1,
    source: "RV Country lot unit record",
    overridesCatalog: { max_sleeping_count: true, number_of_slideouts: true },
    sourceNote:
      "public/inventory/own-lot-latest.json · scraped 2026-09-25 · GVWR, UVW/dry, Hitch/pin, Length (ft), Fresh (gal), Gray (gal), Black (gal), Sleeps, Slides · id 98173 / stock 46454; id 99335 / stock 46561; id 130330 / stock 47262 · Overrides catalog: Sleeps 3 replaces 6 (rvData series seed); Slides 1 replaces 0 (rvData series seed)",
  },
  {
    year: 2027,
    make: "Grand Design",
    model: "Imagine XLS",
    trim: "22BHE",
    title: "2027 Grand Design Imagine XLS 22BHE",
    stock_number: "47436",
    gvwr: 6995,
    dry_weight: 5698,
    hitch_weight: 543,
    propane_lbs: 40,
    total_fresh_water_tank_capacity: 37,
    total_gray_water_tank_capacity: 45,
    total_black_water_tank_capacity: 37,
    number_of_slideouts: 2,
    source: "RV Country lot unit record",
    overridesCatalog: { number_of_slideouts: true },
    sourceNote:
      "public/inventory/own-lot-latest.json · scraped 2026-09-25 · GVWR, UVW/dry, Hitch/pin, Propane (lb), Fresh (gal), Gray (gal), Black (gal), Slides · id 150539 / stock 47436 · Overrides catalog: Slides 2 replaces 0 (rvData series seed)",
  },
  {
    year: 2027,
    make: "Grand Design",
    model: "Imagine XLS",
    trim: "22MLE",
    title: "2027 Grand Design Imagine XLS 22MLE",
    stock_number: "47441 / 47569 / 47570",
    gvwr: 6995,
    dry_weight: 5358,
    hitch_weight: 490,
    vehicle_body_length: 26.08,
    propane_lbs: 40,
    total_fresh_water_tank_capacity: 43,
    total_gray_water_tank_capacity: 45,
    total_black_water_tank_capacity: 37,
    max_sleeping_count: 4,
    number_of_slideouts: 1,
    source: "RV Country lot unit record",
    overridesCatalog: { max_sleeping_count: true, number_of_slideouts: true },
    sourceNote:
      "public/inventory/own-lot-latest.json · scraped 2026-09-25 · GVWR, UVW/dry, Hitch/pin, Length (ft), Propane (lb), Fresh (gal), Gray (gal), Black (gal), Sleeps, Slides · id 150544 / stock 47441; id 178493 / stock 47569; id 178495 / stock 47570 · Overrides catalog: Sleeps 4 replaces 6 (rvData series seed); Slides 1 replaces 0 (rvData series seed)",
  },
  {
    year: 2027,
    make: "Grand Design",
    model: "Imagine XLS",
    trim: "23LDE",
    title: "2027 Grand Design Imagine XLS 23LDE",
    stock_number: "47859",
    gvwr: 6995,
    dry_weight: 5711,
    hitch_weight: 650,
    propane_lbs: 40,
    total_fresh_water_tank_capacity: 37,
    total_gray_water_tank_capacity: 82,
    total_black_water_tank_capacity: 37,
    max_sleeping_count: 4,
    number_of_slideouts: 1,
    source: "RV Country lot unit record",
    overridesCatalog: { max_sleeping_count: true, number_of_slideouts: true },
    sourceNote:
      "public/inventory/own-lot-latest.json · scraped 2026-09-25 · GVWR, UVW/dry, Hitch/pin, Propane (lb), Fresh (gal), Gray (gal), Black (gal), Sleeps, Slides · id 214460 / stock 47859 · Overrides catalog: Sleeps 4 replaces 6 (rvData series seed); Slides 1 replaces 0 (rvData series seed)",
  },
];
