/**
 * Hard brochure corrections for known catalog / Live Grok mistakes.
 * These ALWAYS win over static rvData defaults AND over Live Grok powertrain
 * fields (engine / HP / torque / chassis / transmission). Expand as we verify.
 */

export type PowertrainCorrection = {
  /** Match year range inclusive */
  yearMin: number;
  yearEnd: number;
  makeIncludes: string;
  modelIncludes: string;
  /** Optional floorplan substring */
  floorplanIncludes?: string;
  engine: string;
  /**
   * Single locked HP. Use 0 when the engine is an option band
   * (e.g. L9 450 std / X15 605 opt) — never treat 450 as the only rating.
   */
  horsepower: number;
  /** Omit when torque is option-band (L9 std vs X15 opt). */
  torqueLbFt?: number;
  chassis?: string;
  transmission?: string;
  fuelType?: "Diesel" | "Gas" | "Propane";
  note?: string;
};

/**
 * Verified / brochure-backed patches. Prefer official MY brochures.
 * Display + cache layers pin these over Live Grok so sibling-model steals
 * (e.g. Allegro Bus ISL on a RED, gas F53 Allegro Open Road on a RED) never stick.
 */
export const POWERTRAIN_CORRECTIONS: PowertrainCorrection[] = [
  {
    yearMin: 2018,
    yearEnd: 2027,
    makeIncludes: "jayco",
    modelIncludes: "seneca",
    engine: "Cummins ISB 6.7L 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner S2RV Plus",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "Jayco Seneca Super C OEM: ISB 6.7 360/800 · S2RV Plus · Allison 3000 MH · 100 gal · hitch 12k — not Power Stroke F-550 default",
  },
  {
    yearMin: 2018,
    yearEnd: 2026,
    makeIncludes: "entegra",
    modelIncludes: "accolade",
    engine: "Cummins ISB 6.7L 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner S2RV Plus",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "Entegra Accolade / Accolade XL is the Seneca sibling: same S2RV Plus · ISB 6.7 360/800 · Allison 3000 MH · 100 gal · hitch 12k",
  },
  {
    yearMin: 2026,
    yearEnd: 2027,
    makeIncludes: "entegra",
    modelIncludes: "centurion",
    floorplanIncludes: "39N",
    engine: "Detroit DD13 GEN 5 12.8L 525HP",
    horsepower: 525,
    torqueLbFt: 1850,
    chassis: "Freightliner Cascadia 116 Day Cab",
    transmission: "12-speed overdrive automated manual",
    fuelType: "Diesel",
    note: "Centurion 39N — Cascadia 116 · DD13 525/1850 · hitch 20k. Not Accolade ISB.",
  },
  {
    yearMin: 2026,
    yearEnd: 2027,
    makeIncludes: "entegra",
    modelIncludes: "centurion",
    floorplanIncludes: "39K",
    engine: "Detroit DD13 GEN 5 12.8L 525HP",
    horsepower: 525,
    torqueLbFt: 1850,
    chassis: "Freightliner Cascadia 116 Day Cab",
    transmission: "12-speed overdrive automated manual",
    fuelType: "Diesel",
    note: "Centurion 39K — Cascadia 116 · DD13 525/1850 · hitch 20k. Not Accolade ISB.",
  },
  {
    yearMin: 2026,
    yearEnd: 2027,
    makeIncludes: "entegra",
    modelIncludes: "centurion",
    floorplanIncludes: "45D",
    engine: "Detroit DD16 15.6L 600HP",
    horsepower: 600,
    torqueLbFt: 1850,
    chassis: "Freightliner Cascadia 126",
    transmission: "12-speed overdrive automated manual",
    fuelType: "Diesel",
    note: "Centurion 45D — Cascadia 126 · DD16 600/1850 · hitch 30k.",
  },
  {
    yearMin: 2026,
    yearEnd: 2027,
    makeIncludes: "entegra",
    modelIncludes: "centurion",
    engine: "Detroit DD13 GEN 5 12.8L 525HP",
    horsepower: 525,
    torqueLbFt: 1850,
    chassis: "Freightliner Cascadia 116 Day Cab",
    transmission: "12-speed overdrive automated manual",
    fuelType: "Diesel",
    note: "Centurion default 39-class DD13 525 — pick 45D for DD16 600",
  },
  {
    yearMin: 2026,
    yearEnd: 2027,
    makeIncludes: "newmar",
    modelIncludes: "grand star",
    engine: "Cummins B6.7 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner S2RV",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "Grand Star Super C — S2RV B 360/800 hitch 12k. Not Cascadia.",
  },
  {
    yearMin: 2025,
    yearEnd: 2027,
    makeIncludes: "newmar",
    modelIncludes: "northern star",
    engine: "Cummins B6.7 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner Custom Chassis",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "Northern Star diesel pusher 360/800 — not Super C.",
  },
  {
    yearMin: 2026,
    yearEnd: 2027,
    makeIncludes: "newmar",
    modelIncludes: "summit aire",
    engine: "Detroit DD16 600HP",
    horsepower: 600,
    torqueLbFt: 1850,
    chassis: "Freightliner Cascadia 126 tandem axle",
    fuelType: "Diesel",
    note: "Summit Aire flagship Super C DD16 600 / 30k hitch",
  },
  {
    yearMin: 2026,
    yearEnd: 2026,
    makeIncludes: "newmar",
    modelIncludes: "freedom aire",
    engine: "Mercedes-Benz 2.0L turbo diesel 208HP",
    horsepower: 208,
    torqueLbFt: 332,
    chassis: "Mercedes-Benz Sprinter 4500",
    fuelType: "Diesel",
    note: "OEM 2026-freedom-aire: Sprinter 4500, 208 / 332, plan 2515 — not a pusher",
  },
  {
    yearMin: 2027,
    yearEnd: 2027,
    makeIncludes: "newmar",
    modelIncludes: "freedom aire",
    engine: "Mercedes-Benz 2.0L turbo diesel 211HP",
    horsepower: 211,
    torqueLbFt: 332,
    chassis: "Mercedes-Benz Sprinter 4500",
    fuelType: "Diesel",
    note: "OEM MY27FA: Sprinter 4500, 211 / 332, plans 2515 + 2512 — not a pusher",
  },
  {
    yearMin: 2026,
    yearEnd: 2027,
    makeIncludes: "newmar",
    modelIncludes: "super star",
    floorplanIncludes: "4140",
    engine: "Cummins 450HP (Freightliner M2-112)",
    horsepower: 450,
    torqueLbFt: 1250,
    chassis: "Freightliner M2-112",
    fuelType: "Diesel",
    note: "Super Star 41 ft M2-112 450",
  },
  {
    yearMin: 2020,
    yearEnd: 2021,
    makeIncludes: "newmar",
    modelIncludes: "super star",
    engine: "Cummins L 350HP (Freightliner M2-106)",
    horsepower: 350,
    chassis: "Freightliner M2-106",
    fuelType: "Diesel",
    note: "OEM MY20–21 Super Star: M2-106 Cummins 350 — not the later 360 rating. Plans 3746/4051/4058/4061. No 2019 brochure.",
  },
  {
    yearMin: 2022,
    yearEnd: 2027,
    makeIncludes: "newmar",
    modelIncludes: "super star",
    engine: "Cummins L 360HP (Freightliner M2-106)",
    horsepower: 360,
    torqueLbFt: 1150,
    chassis: "Freightliner M2-106",
    fuelType: "Diesel",
    note: "Super Star 37–40 default M2-106 360 (OEM MY22 360/1150; MY23–25 all plans 360; MY26+ 41' is 450)",
  },
  {
    yearMin: 2026,
    yearEnd: 2027,
    makeIncludes: "grand design",
    modelIncludes: "lineage series e",
    engine: "Ford 7.3L V8 gas 325HP",
    horsepower: 325,
    torqueLbFt: 450,
    chassis: "Ford Econoline E-450 DRW",
    transmission: "6-speed TorqShift",
    fuelType: "Gas",
    note: "Lineage Series E — E-450 7.3 gas 325/450 · hitch 7,500. Not Sprinter.",
  },
  {
    yearMin: 2025,
    yearEnd: 2027,
    makeIncludes: "grand design",
    modelIncludes: "lineage series m",
    engine: "Mercedes-Benz 2.0L twin-turbo diesel 208HP",
    horsepower: 208,
    torqueLbFt: 332,
    chassis: "Mercedes-Benz Sprinter 4500",
    transmission: "9G-Tronic automatic",
    fuelType: "Diesel",
    note: "Lineage Series M — Sprinter 4500 208/332. Not E-450 gas.",
  },
  {
    yearMin: 2025,
    yearEnd: 2027,
    makeIncludes: "grand design",
    modelIncludes: "lineage series f",
    engine: "Ford 6.7L Power Stroke 330HP",
    horsepower: 330,
    torqueLbFt: 950,
    chassis: "Ford Super Duty 4x4",
    transmission: "10-speed automatic",
    fuelType: "Diesel",
    note: "Lineage Series F — Power Stroke 6.7 Super C 4x4. 31ZW F-600 15k hitch.",
  },
  {
    yearMin: 2026,
    yearEnd: 2027,
    makeIncludes: "grand design",
    modelIncludes: "lineage series vt",
    engine: "Ford 3.5L EcoBoost V6 310HP",
    horsepower: 310,
    torqueLbFt: 400,
    chassis: "Ford Transit 350 AWD",
    transmission: "10-speed automatic",
    fuelType: "Gas",
    note: "Lineage Series VT LVT1 — Transit AWD EcoBoost 310/400.",
  },
  {
    yearMin: 2020,
    yearEnd: 2026,
    makeIncludes: "jayco",
    modelIncludes: "precept",
    engine: "Ford 7.3L V8 Godzilla 335HP",
    horsepower: 335,
    torqueLbFt: 468,
    chassis: "Ford F53",
    transmission: "TorqShift 6-speed automatic",
    fuelType: "Gas",
    note: "Precept is gas F53 335/468 — not diesel X15",
  },
  {
    yearMin: 2020,
    yearEnd: 2026,
    makeIncludes: "jayco",
    modelIncludes: "alante",
    engine: "Ford 7.3L V8 Godzilla 335HP",
    horsepower: 335,
    torqueLbFt: 468,
    chassis: "Ford F53",
    transmission: "TorqShift 6-speed automatic",
    fuelType: "Gas",
    note: "Alante gas F53 — not diesel",
  },

  {
    yearMin: 2020,
    yearEnd: 2026,
    makeIncludes: "thor",
    modelIncludes: "vegas",
    engine: "Ford 7.3L V8 (Godzilla) 325HP",
    horsepower: 325,
    torqueLbFt: 450,
    chassis: "Ford E-Series cutaway (Class A body)",
    transmission: "TorqShift automatic",
    fuelType: "Gas",
    note: "Vegas compact RUV — cutaway chassis NOT F53; Thor OEM 325/450, 55 gal, hitch 8k",
  },
  {
    yearMin: 2020,
    yearEnd: 2026,
    makeIncludes: "thor",
    modelIncludes: "axis",
    engine: "Ford 7.3L V8 (Godzilla) 325HP",
    horsepower: 325,
    torqueLbFt: 450,
    chassis: "Ford E-Series cutaway (Class A body)",
    transmission: "TorqShift automatic",
    fuelType: "Gas",
    note: "Axis sister to Vegas — same cutaway 7.3L package, not F53 ACE/Windsport",
  },
  {
    yearMin: 2014,
    yearEnd: 2019,
    makeIncludes: "thor",
    modelIncludes: "vegas",
    engine: "Ford Triton V10 6.8L",
    horsepower: 305,
    torqueLbFt: 420,
    chassis: "Ford E-350 / E-450 cutaway",
    fuelType: "Gas",
    note: "Early Vegas V10 cutaway",
  },
  {
    yearMin: 2014,
    yearEnd: 2019,
    makeIncludes: "thor",
    modelIncludes: "axis",
    engine: "Ford Triton V10 6.8L",
    horsepower: 305,
    torqueLbFt: 420,
    chassis: "Ford E-350 / E-450 cutaway",
    fuelType: "Gas",
    note: "Early Axis V10 cutaway",
  },

  // Fleetwood Discovery (regular, not LXE) — Cummins ISB / B6.7 class, not 8.9 ISL
  {
    yearMin: 2018,
    yearEnd: 2024,
    makeIncludes: "fleetwood",
    modelIncludes: "discovery",
    engine: "Cummins B6.7 (ISB)",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner XC-Series",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "Regular Discovery — not LXE / not ISL 8.9",
  },
  {
    yearMin: 2017,
    yearEnd: 2018,
    makeIncludes: "fleetwood",
    modelIncludes: "discovery lxe",
    engine: "Cummins ISB 6.7 360HP / ISL9 380HP / ISL9 450HP (by floorplan)",
    horsepower: 0,
    chassis: "Freightliner Custom Chassis XCM",
    transmission: "Allison 3000 MH 6-Speed",
    fuelType: "Diesel",
    note: "MY17 RVUSA LXE: 40D/40E/40G/40X = ISL9 380/1150. MY18 DISDISLXE18B1: 38K/39F = ISB 360/800; 40-ft = ISL9 380/1150; 44H = ISL9 450/1250.",
  },
  {
    yearMin: 2018,
    yearEnd: 2018,
    makeIncludes: "fleetwood",
    modelIncludes: "discovery lxe",
    floorplanIncludes: "38K",
    engine: "Cummins ISB 6.7 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner Custom Chassis XCM",
    transmission: "Allison 3000 MH 6-Speed",
    fuelType: "Diesel",
    note: "MY18 LXE brochure 38K — ISB 6.7 360 / 800 (not ISL9).",
  },
  {
    yearMin: 2018,
    yearEnd: 2018,
    makeIncludes: "fleetwood",
    modelIncludes: "discovery lxe",
    floorplanIncludes: "39F",
    engine: "Cummins ISB 6.7 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner Custom Chassis XCM",
    transmission: "Allison 3000 MH 6-Speed",
    fuelType: "Diesel",
    note: "MY18 LXE brochure 39F — ISB 6.7 360 / 800 (not ISL9).",
  },
  {
    yearMin: 2017,
    yearEnd: 2018,
    makeIncludes: "fleetwood",
    modelIncludes: "discovery lxe",
    floorplanIncludes: "40D",
    engine: "Cummins ISL9 380HP",
    horsepower: 380,
    torqueLbFt: 1150,
    chassis: "Freightliner Custom Chassis XCM",
    transmission: "Allison 3000 MH 6-Speed",
    fuelType: "Diesel",
    note: "MY17/MY18 LXE 40D — ISL9 380 / 1,150",
  },
  {
    yearMin: 2017,
    yearEnd: 2018,
    makeIncludes: "fleetwood",
    modelIncludes: "discovery lxe",
    floorplanIncludes: "40E",
    engine: "Cummins ISL9 380HP",
    horsepower: 380,
    torqueLbFt: 1150,
    chassis: "Freightliner Custom Chassis XCM",
    transmission: "Allison 3000 MH 6-Speed",
    fuelType: "Diesel",
    note: "MY17/MY18 LXE 40E — ISL9 380 / 1,150",
  },
  {
    yearMin: 2017,
    yearEnd: 2018,
    makeIncludes: "fleetwood",
    modelIncludes: "discovery lxe",
    floorplanIncludes: "40G",
    engine: "Cummins ISL9 380HP",
    horsepower: 380,
    torqueLbFt: 1150,
    chassis: "Freightliner Custom Chassis XCM",
    transmission: "Allison 3000 MH 6-Speed",
    fuelType: "Diesel",
    note: "MY17/MY18 LXE 40G — ISL9 380 / 1,150",
  },
  {
    yearMin: 2017,
    yearEnd: 2018,
    makeIncludes: "fleetwood",
    modelIncludes: "discovery lxe",
    floorplanIncludes: "40X",
    engine: "Cummins ISL9 380HP",
    horsepower: 380,
    torqueLbFt: 1150,
    chassis: "Freightliner Custom Chassis XCM",
    transmission: "Allison 3000 MH 6-Speed",
    fuelType: "Diesel",
    note: "MY17/MY18 LXE 40X — ISL9 380 / 1,150",
  },
  {
    yearMin: 2018,
    yearEnd: 2018,
    makeIncludes: "fleetwood",
    modelIncludes: "discovery lxe",
    floorplanIncludes: "44H",
    engine: "Cummins ISL9 450HP",
    horsepower: 450,
    torqueLbFt: 1250,
    chassis: "Freightliner Custom Chassis XCM",
    transmission: "Allison 3000 MH 6-Speed",
    fuelType: "Diesel",
    note: "MY18 LXE brochure 44H — ISL9 450 / 1,250",
  },
  {
    yearMin: 2019,
    yearEnd: 2020,
    makeIncludes: "fleetwood",
    modelIncludes: "discovery lxe",
    engine: "Cummins ISL 9L 380HP / 450HP (by floorplan)",
    horsepower: 0,
    chassis: "Freightliner Custom Chassis XCM",
    transmission: "Allison 3000 MH 6-Speed",
    fuelType: "Diesel",
    note: "MY19/MY20 LXE brochures: 40D/40G/40M = ISL 9L 380 / 1,150; 44B/44H = ISL 9L 450 / 1,250.",
  },
  {
    yearMin: 2019,
    yearEnd: 2020,
    makeIncludes: "fleetwood",
    modelIncludes: "discovery lxe",
    floorplanIncludes: "40D",
    engine: "Cummins ISL 9L 380HP",
    horsepower: 380,
    torqueLbFt: 1150,
    chassis: "Freightliner Custom Chassis XCM",
    transmission: "Allison 3000 MH 6-Speed",
    fuelType: "Diesel",
    note: "MY19/MY20 LXE brochure 40D — ISL 9L 380 / 1,150",
  },
  {
    yearMin: 2019,
    yearEnd: 2020,
    makeIncludes: "fleetwood",
    modelIncludes: "discovery lxe",
    floorplanIncludes: "40G",
    engine: "Cummins ISL 9L 380HP",
    horsepower: 380,
    torqueLbFt: 1150,
    chassis: "Freightliner Custom Chassis XCM",
    transmission: "Allison 3000 MH 6-Speed",
    fuelType: "Diesel",
    note: "MY19/MY20 LXE brochure 40G — ISL 9L 380 / 1,150",
  },
  {
    yearMin: 2019,
    yearEnd: 2020,
    makeIncludes: "fleetwood",
    modelIncludes: "discovery lxe",
    floorplanIncludes: "40M",
    engine: "Cummins ISL 9L 380HP",
    horsepower: 380,
    torqueLbFt: 1150,
    chassis: "Freightliner Custom Chassis XCM",
    transmission: "Allison 3000 MH 6-Speed",
    fuelType: "Diesel",
    note: "MY19/MY20 LXE brochure 40M — ISL 9L 380 / 1,150",
  },
  {
    yearMin: 2019,
    yearEnd: 2020,
    makeIncludes: "fleetwood",
    modelIncludes: "discovery lxe",
    floorplanIncludes: "44B",
    engine: "Cummins ISL 9L 450HP",
    horsepower: 450,
    torqueLbFt: 1250,
    chassis: "Freightliner Custom Chassis XCM",
    transmission: "Allison 3000 MH 6-Speed",
    fuelType: "Diesel",
    note: "MY19/MY20 LXE brochure 44B — ISL 9L 450 / 1,250",
  },
  {
    yearMin: 2019,
    yearEnd: 2020,
    makeIncludes: "fleetwood",
    modelIncludes: "discovery lxe",
    floorplanIncludes: "44H",
    engine: "Cummins ISL 9L 450HP",
    horsepower: 450,
    torqueLbFt: 1250,
    chassis: "Freightliner Custom Chassis XCM",
    transmission: "Allison 3000 MH 6-Speed",
    fuelType: "Diesel",
    note: "MY19/MY20 LXE brochure 44H — ISL 9L 450 / 1,250",
  },
  {
    yearMin: 2021,
    yearEnd: 2022,
    makeIncludes: "fleetwood",
    modelIncludes: "discovery lxe",
    engine: "Cummins L9 380HP / 450HP (by floorplan)",
    horsepower: 0,
    chassis: "Freightliner Custom Chassis XCM",
    transmission: "Allison 3000 MH 6-Speed",
    fuelType: "Diesel",
    note: "MY21 LXE brochure: 36HQ/40D/40G/40M = L9 380 / 1,150; 44B/44H/44S = L9 450 / 1,250. MY22 drops 40D/44H.",
  },
  {
    yearMin: 2021,
    yearEnd: 2022,
    makeIncludes: "fleetwood",
    modelIncludes: "discovery lxe",
    floorplanIncludes: "36HQ",
    engine: "Cummins L9 380HP",
    horsepower: 380,
    torqueLbFt: 1150,
    chassis: "Freightliner Custom Chassis XCM",
    transmission: "Allison 3000 MH 6-Speed",
    fuelType: "Diesel",
    note: "MY21 LXE brochure 36HQ — L9 380 / 1,150",
  },
  {
    yearMin: 2021,
    yearEnd: 2021,
    makeIncludes: "fleetwood",
    modelIncludes: "discovery lxe",
    floorplanIncludes: "40D",
    engine: "Cummins L9 380HP",
    horsepower: 380,
    torqueLbFt: 1150,
    chassis: "Freightliner Custom Chassis XCM",
    transmission: "Allison 3000 MH 6-Speed",
    fuelType: "Diesel",
    note: "MY21 LXE brochure 40D — L9 380 / 1,150. Dropped MY22.",
  },
  {
    yearMin: 2021,
    yearEnd: 2022,
    makeIncludes: "fleetwood",
    modelIncludes: "discovery lxe",
    floorplanIncludes: "40G",
    engine: "Cummins L9 380HP",
    horsepower: 380,
    torqueLbFt: 1150,
    chassis: "Freightliner Custom Chassis XCM",
    transmission: "Allison 3000 MH 6-Speed",
    fuelType: "Diesel",
    note: "MY21 LXE brochure 40G — L9 380 / 1,150",
  },
  {
    yearMin: 2021,
    yearEnd: 2022,
    makeIncludes: "fleetwood",
    modelIncludes: "discovery lxe",
    floorplanIncludes: "40M",
    engine: "Cummins L9 380HP",
    horsepower: 380,
    torqueLbFt: 1150,
    chassis: "Freightliner Custom Chassis XCM",
    transmission: "Allison 3000 MH 6-Speed",
    fuelType: "Diesel",
    note: "MY21 LXE brochure 40M — L9 380 / 1,150",
  },
  {
    yearMin: 2021,
    yearEnd: 2022,
    makeIncludes: "fleetwood",
    modelIncludes: "discovery lxe",
    floorplanIncludes: "44B",
    engine: "Cummins L9 450HP",
    horsepower: 450,
    torqueLbFt: 1250,
    chassis: "Freightliner Custom Chassis XCM",
    transmission: "Allison 3000 MH 6-Speed",
    fuelType: "Diesel",
    note: "MY21 LXE brochure 44B — L9 450 / 1,250",
  },
  {
    yearMin: 2021,
    yearEnd: 2021,
    makeIncludes: "fleetwood",
    modelIncludes: "discovery lxe",
    floorplanIncludes: "44H",
    engine: "Cummins L9 450HP",
    horsepower: 450,
    torqueLbFt: 1250,
    chassis: "Freightliner Custom Chassis XCM",
    transmission: "Allison 3000 MH 6-Speed",
    fuelType: "Diesel",
    note: "MY21 LXE brochure 44H — L9 450 / 1,250. Dropped MY22.",
  },
  {
    yearMin: 2021,
    yearEnd: 2022,
    makeIncludes: "fleetwood",
    modelIncludes: "discovery lxe",
    floorplanIncludes: "44S",
    engine: "Cummins L9 450HP",
    horsepower: 450,
    torqueLbFt: 1250,
    chassis: "Freightliner Custom Chassis XCM",
    transmission: "Allison 3000 MH 6-Speed",
    fuelType: "Diesel",
    note: "MY21 LXE brochure 44S — L9 450 / 1,250",
  },
  {
    yearMin: 2023,
    yearEnd: 2024,
    makeIncludes: "fleetwood",
    modelIncludes: "discovery lxe",
    engine: "Cummins L9 380HP / 450HP (by floorplan)",
    horsepower: 0,
    chassis: "Freightliner Custom Chassis XCM",
    transmission: "Allison 3000 MH 6-Speed",
    fuelType: "Diesel",
    note: "LXE24F1 / OEM 2023: 40G/40M = L9 380 / 1,150; 44B/44S = L9 450 / 1,250. 36HQ MY23 only — confirm plan, do not invent a single HP.",
  },
  {
    yearMin: 2023,
    yearEnd: 2024,
    makeIncludes: "fleetwood",
    modelIncludes: "discovery lxe",
    floorplanIncludes: "40G",
    engine: "Cummins L9 380HP",
    horsepower: 380,
    torqueLbFt: 1150,
    chassis: "Freightliner Custom Chassis XCM",
    transmission: "Allison 3000 MH 6-Speed",
    fuelType: "Diesel",
    note: "LXE24F1 40G — L9 380 / 1,150",
  },
  {
    yearMin: 2023,
    yearEnd: 2024,
    makeIncludes: "fleetwood",
    modelIncludes: "discovery lxe",
    floorplanIncludes: "40M",
    engine: "Cummins L9 380HP",
    horsepower: 380,
    torqueLbFt: 1150,
    chassis: "Freightliner Custom Chassis XCM",
    transmission: "Allison 3000 MH 6-Speed",
    fuelType: "Diesel",
    note: "LXE24F1 40M — L9 380 / 1,150",
  },
  {
    yearMin: 2023,
    yearEnd: 2024,
    makeIncludes: "fleetwood",
    modelIncludes: "discovery lxe",
    floorplanIncludes: "44B",
    engine: "Cummins L9 450HP",
    horsepower: 450,
    torqueLbFt: 1250,
    chassis: "Freightliner Custom Chassis XCM",
    transmission: "Allison 3000 MH 6-Speed",
    fuelType: "Diesel",
    note: "LXE24F1 44B — L9 450 / 1,250",
  },
  {
    yearMin: 2023,
    yearEnd: 2024,
    makeIncludes: "fleetwood",
    modelIncludes: "discovery lxe",
    floorplanIncludes: "44S",
    engine: "Cummins L9 450HP",
    horsepower: 450,
    torqueLbFt: 1250,
    chassis: "Freightliner Custom Chassis XCM",
    transmission: "Allison 3000 MH 6-Speed",
    fuelType: "Diesel",
    note: "LXE24F1 44S — L9 450 / 1,250",
  },
  // Entegra Reatta — mid diesel B6.7, not Aspire/Anthem L9
  {
    yearMin: 2018,
    yearEnd: 2026,
    makeIncludes: "entegra",
    modelIncludes: "reatta",
    engine: "Cummins B6.7 turbo diesel",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Spartan K1 raised-rail",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "Reatta diesel — not Aspire/Anthem L9",
  },
  // American Coach American Dream — option band, not a single invented HP
  {
    yearMin: 2020,
    yearEnd: 2026,
    makeIncludes: "american coach",
    modelIncludes: "american dream",
    engine: "Cummins L9 450 std / X15 605 opt",
    horsepower: 0,
    chassis: "Spartan K3",
    transmission: "Allison 3000/4000",
    fuelType: "Diesel",
    note: "2020–2026 American Dream (2023 floorplans 45A / 45B): L9 450 / 1,250 lb-ft standard, X15 605 / ~1,850–1,950 lb-ft optional. Confirm door sticker. Not Tradition Liberty Bridge. Do not invent a single HP or L9-only torque.",
  },
  // Entegra Vision — gas F53 Godzilla only
  {
    yearMin: 2019,
    yearEnd: 2026,
    makeIncludes: "entegra",
    modelIncludes: "vision",
    engine: "Ford 7.3L V8 Godzilla",
    horsepower: 350,
    torqueLbFt: 468,
    chassis: "Ford F-53",
    transmission: "TorqShift 6-speed automatic",
    fuelType: "Gas",
    note: "Vision gas F-53 only — never diesel",
  },
  {
    yearMin: 2016,
    yearEnd: 2020,
    makeIncludes: "newmar",
    modelIncludes: "bay star",
    engine: "Ford Triton V10 6.8L 320HP",
    horsepower: 320,
    chassis: "Ford F53",
    transmission: "TorqShift automatic",
    fuelType: "Gas",
    note: "OEM MY17–20 Bay Star / Sport: F53 Triton V10 320 — gas, not 7.3 Godzilla (MY21+) and not diesel. Not Kountry Star.",
  },
  {
    yearMin: 2021,
    yearEnd: 2023,
    makeIncludes: "newmar",
    modelIncludes: "bay star",
    engine: "Ford 7.3L V8 Godzilla 350HP",
    horsepower: 350,
    torqueLbFt: 468,
    chassis: "Ford F53",
    transmission: "TorqShift 6-speed automatic",
    fuelType: "Gas",
    note: "OEM MY21–23 Bay Star / Bay Star Sport chassis table: F53 7.3 350 / 468 — gas, not diesel. Not the later 335 rating.",
  },
  {
    yearMin: 2024,
    yearEnd: 2027,
    makeIncludes: "newmar",
    modelIncludes: "bay star",
    engine: "Ford 7.3L V8 Godzilla 335HP",
    horsepower: 335,
    torqueLbFt: 468,
    chassis: "Ford F53",
    transmission: "TorqShift 6-speed automatic",
    fuelType: "Gas",
    note: "OEM MY24–27 Bay Star / Sport: F53 7.3 335 / 468 — gas, not diesel L9 450; not Kountry Star",
  },
  // Forest River FR3 — gas F53 only (OEM brochure 335 HP / 468 lb-ft Godzilla)
  {
    yearMin: 2020,
    yearEnd: 2026,
    makeIncludes: "forest river",
    modelIncludes: "fr3",
    engine: "Ford 7.3L V8 Godzilla",
    horsepower: 335,
    torqueLbFt: 468,
    chassis: "Ford F53",
    transmission: "TorqShift 6-speed automatic",
    fuelType: "Gas",
    note: "FR3 gas Class A — Ford 7.3 Godzilla 335/468 on F53; not diesel",
  },
  {
    yearMin: 2015,
    yearEnd: 2019,
    makeIncludes: "forest river",
    modelIncludes: "fr3",
    engine: "Ford Triton V10 6.8L",
    horsepower: 320,
    chassis: "Ford F53",
    transmission: "TorqShift automatic",
    fuelType: "Gas",
    note: "FR3 pre-Godzilla Triton V10 era",
  },
  // Newmar Kountry Star — diesel pusher (NOT gas F53 / Godzilla; NOT Dutch Star L9 450)
  {
    yearMin: 2020,
    yearEnd: 2024,
    makeIncludes: "newmar",
    modelIncludes: "kountry star",
    engine: "Cummins B6.7 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner XCR",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "Kountry Star diesel pusher — Cummins B6.7 360/800 on Freightliner XCR (OEM). Not Bay Star 7.3 gas, not Dutch Star L9 450",
  },
  {
    yearMin: 2012,
    yearEnd: 2016,
    makeIncludes: "newmar",
    modelIncludes: "kountry star",
    engine: "Cummins ISB / B6.7 diesel",
    horsepower: 340,
    torqueLbFt: 700,
    chassis: "Freightliner XC / XCR",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "Kountry Star mid-diesel — not Ford F53 gas, not L9 450. No OEM MY17–MY19 brochure (reintroduced MY20 at 360).",
  },
  // Thor Palazzo / Hurricane mid bands (common mixups)
  {
    yearMin: 2018,
    yearEnd: 2026,
    makeIncludes: "thor",
    modelIncludes: "palazzo",
    engine: "Cummins B6.7 (ISB) 340HP",
    horsepower: 340,
    torqueLbFt: 700,
    chassis: "Freightliner XC-S",
    transmission: "Allison 2100 / 2500 MH",
    fuelType: "Diesel",
    note: "Palazzo mid-diesel — not ISL 8.9",
  },
  {
    yearMin: 2016,
    yearEnd: 2026,
    makeIncludes: "winnebago",
    modelIncludes: "forza",
    engine: "Cummins B6.7 (ISB) 340HP",
    horsepower: 340,
    torqueLbFt: 700,
    chassis: "Freightliner XC",
    fuelType: "Diesel",
    note: "Forza mid-diesel — not ISL 8.9",
  },
  {
    yearMin: 2016,
    yearEnd: 2026,
    makeIncludes: "winnebago",
    modelIncludes: "journey",
    engine: "Cummins B6.7 / ISB 340HP",
    horsepower: 340,
    torqueLbFt: 700,
    chassis: "Freightliner XC",
    fuelType: "Diesel",
    note: "Journey diesel — B6.7 class not ISL",
  },
  {
    yearMin: 2016,
    yearEnd: 2026,
    makeIncludes: "winnebago",
    modelIncludes: "adventurer",
    engine: "Ford 6.8L V10 / 7.3L Godzilla (by year)",
    horsepower: 320,
    chassis: "Ford F53",
    fuelType: "Gas",
    note: "Post-V10 F53 gas Class A",
  },
  // Tiffin Allegro RED (legacy nameplate) — diesel mid-coach, NEVER Ford V10 and NEVER ISL 8.9 bus class
  {
    yearMin: 2010,
    yearEnd: 2013,
    makeIncludes: "tiffin",
    modelIncludes: "allegro red",
    engine: "Cummins ISB 6.7L 340HP",
    horsepower: 340,
    torqueLbFt: 700,
    chassis: "Freightliner XC raised-rail",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "Allegro RED diesel pusher — not Ford F53 V10 gas",
  },
  {
    yearMin: 2014,
    yearEnd: 2017,
    makeIncludes: "tiffin",
    modelIncludes: "allegro red",
    engine: "Cummins ISB / B6.7 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner XC / XCR raised-rail",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "2014–2017 Allegro RED mid-diesel — not ISL 8.9 / not L9 flagship",
  },
  {
    yearMin: 2014,
    yearEnd: 2017,
    makeIncludes: "tiffin",
    modelIncludes: "allegro red 340",
    engine: "Cummins ISB / B6.7 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner XC / XCR raised-rail",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "RED 340 2014–2017 — mid-diesel only",
  },
  {
    yearMin: 2018,
    yearEnd: 2026,
    makeIncludes: "tiffin",
    modelIncludes: "allegro red 340",
    engine: "Cummins B6.7 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner XC-Series",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "RED 340 mid-diesel — not L9/ISL bus class",
  },
  {
    yearMin: 2019,
    yearEnd: 2026,
    makeIncludes: "tiffin",
    modelIncludes: "allegro bus",
    engine: "Cummins L9 450HP (X12 optional)",
    horsepower: 450,
    torqueLbFt: 1250,
    chassis: "Tiffin PowerGlide",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
  },
  {
    yearMin: 2016,
    yearEnd: 2026,
    makeIncludes: "tiffin",
    modelIncludes: "phaeton",
    floorplanIncludes: "37bh",
    engine: "Cummins L9 380HP",
    horsepower: 380,
    torqueLbFt: 1150,
    chassis: "Freightliner / Tiffin PowerGlide (by option)",
    transmission: "Allison 3000 MH 6-speed",
    fuelType: "Diesel",
    note:
      "37BH Phaeton OEM: L9 380 / 1,150 only — 450 was NOT offered on 37BH.",
  },
  {
    yearMin: 2016,
    yearEnd: 2026,
    makeIncludes: "tiffin",
    modelIncludes: "phaeton",
    floorplanIncludes: "44oh",
    engine: "Cummins L9 380HP (450 optional on tag axle)",
    horsepower: 380,
    torqueLbFt: 1150,
    chassis: "Freightliner / Tiffin PowerGlide (by option)",
    transmission: "Allison 3000 MH 6-speed",
    fuelType: "Diesel",
    note: "44OH — 380 standard; 450 may be available. Confirm build.",
  },
  {
    yearMin: 2016,
    yearEnd: 2026,
    makeIncludes: "tiffin",
    modelIncludes: "phaeton",
    engine: "Cummins L9 380HP",
    horsepower: 380,
    torqueLbFt: 1150,
    chassis: "Freightliner / Tiffin PowerGlide (by option)",
    transmission: "Allison 3000 MH 6-speed",
    fuelType: "Diesel",
    note:
      "Phaeton brochure default L9 380/1150. 450 only on select floorplans (not 37BH).",
  },
  {
    yearMin: 2017,
    yearEnd: 2017,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    engine: "Cummins ISB 360HP (34–37') or ISL 400HP (40–43')",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner XCR",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM 2017_Ventana year-first: 34–37' ISB 360 / 40–43' ISL 400. Bare ventana must not stamp Ventana LE.",
  },
  {
    yearMin: 2018,
    yearEnd: 2018,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    engine: "Cummins B 360HP (34–37') or L 400HP (40–43')",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner XCR",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM 2018_Ventana year-first: 34–37' Cummins B 360 / 40–43' Cummins L 400.",
  },
  {
    yearMin: 2017,
    yearEnd: 2018,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "3412",
    engine: "Cummins ISB / B 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner XCR",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM MY17–18 Ventana 34' 3412: 360 — not ISL/L 400",
  },
  {
    yearMin: 2017,
    yearEnd: 2018,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "3436",
    engine: "Cummins ISB / B 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner XCR",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM MY17–18 Ventana 34' 3436: 360 — not ISL/L 400",
  },
  {
    yearMin: 2017,
    yearEnd: 2018,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "3709",
    engine: "Cummins ISB / B 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner XCR",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM MY17–18 Ventana 37' 3709: 360 — not ISL/L 400",
  },
  {
    yearMin: 2017,
    yearEnd: 2017,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "3724",
    engine: "Cummins ISB 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner XCR",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM 2017_Ventana 37' 3724: ISB 360",
  },
  {
    yearMin: 2018,
    yearEnd: 2018,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "3407",
    engine: "Cummins B 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner XCR",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM 2018_Ventana 34' 3407: Cummins B 360",
  },
  {
    yearMin: 2018,
    yearEnd: 2018,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "3715",
    engine: "Cummins B 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner XCR",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM 2018_Ventana 37' 3715: Cummins B 360",
  },
  {
    yearMin: 2017,
    yearEnd: 2018,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "4002",
    engine: "Cummins ISL / L 400HP",
    horsepower: 400,
    torqueLbFt: 1250,
    chassis: "Freightliner XCR Tag",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM MY17–18 Ventana 40' 4002: ISL/L 400 — not ISB/B 360",
  },
  {
    yearMin: 2017,
    yearEnd: 2018,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "4037",
    engine: "Cummins ISL / L 400HP",
    horsepower: 400,
    torqueLbFt: 1250,
    chassis: "Freightliner XCR Tag",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM MY17–18 Ventana 40' 4037: ISL/L 400",
  },
  {
    yearMin: 2017,
    yearEnd: 2017,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "4041",
    engine: "Cummins ISL 400HP",
    horsepower: 400,
    torqueLbFt: 1250,
    chassis: "Freightliner XCR Tag",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM 2017_Ventana 40' 4041: ISL 400",
  },
  {
    yearMin: 2017,
    yearEnd: 2018,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "4310",
    engine: "Cummins ISL / L 400HP",
    horsepower: 400,
    torqueLbFt: 1250,
    chassis: "Freightliner XCR Tag",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM MY17–18 Ventana 43' 4310: ISL/L 400",
  },
  {
    yearMin: 2017,
    yearEnd: 2018,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "4311",
    engine: "Cummins ISL / L 400HP",
    horsepower: 400,
    torqueLbFt: 1250,
    chassis: "Freightliner XCR Tag",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM MY17–18 Ventana 43' 4311: ISL/L 400",
  },
  {
    yearMin: 2017,
    yearEnd: 2017,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "4322",
    engine: "Cummins ISL 400HP",
    horsepower: 400,
    torqueLbFt: 1250,
    chassis: "Freightliner XCR Tag",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM 2017_Ventana 43' 4322: ISL 400",
  },
  {
    yearMin: 2017,
    yearEnd: 2018,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "4369",
    engine: "Cummins ISL / L 400HP",
    horsepower: 400,
    torqueLbFt: 1250,
    chassis: "Freightliner XCR Tag",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM MY17–18 Ventana 43' 4369: ISL/L 400",
  },
  {
    yearMin: 2018,
    yearEnd: 2018,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "4046",
    engine: "Cummins L 400HP",
    horsepower: 400,
    torqueLbFt: 1250,
    chassis: "Freightliner XCR Tag",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM 2018_Ventana 40' 4046: Cummins L 400",
  },
  {
    yearMin: 2018,
    yearEnd: 2018,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "4049",
    engine: "Cummins L 400HP",
    horsepower: 400,
    torqueLbFt: 1250,
    chassis: "Freightliner XCR Tag",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM 2018_Ventana 40' 4049: Cummins L 400",
  },
  {
    yearMin: 2018,
    yearEnd: 2018,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "4308",
    engine: "Cummins L 400HP",
    horsepower: 400,
    torqueLbFt: 1250,
    chassis: "Freightliner XCR Tag",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM 2018_Ventana 43' 4308: Cummins L 400",
  },
  {
    yearMin: 2018,
    yearEnd: 2018,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "4326",
    engine: "Cummins L 400HP",
    horsepower: 400,
    torqueLbFt: 1250,
    chassis: "Freightliner XCR Tag",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM 2018_Ventana 43' 4326: Cummins L 400",
  },
  {
    yearMin: 2019,
    yearEnd: 2023,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "4037",
    engine: "Cummins L9 400HP",
    horsepower: 400,
    torqueLbFt: 1250,
    chassis: "Freightliner XCR Tag / Spartan K2 Tag",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "Ventana 40-ft class — OEM L9 400/1250 (not B6.7 360)",
  },
  {
    yearMin: 2020,
    yearEnd: 2023,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "4041",
    engine: "Cummins L9 400HP",
    horsepower: 400,
    torqueLbFt: 1250,
    chassis: "Freightliner XCR Tag / Spartan K2 Tag",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "Ventana 40-ft class — OEM L9 400/1250",
  },
  {
    yearMin: 2019,
    yearEnd: 2023,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "4369",
    engine: "Cummins L9 400HP",
    horsepower: 400,
    torqueLbFt: 1250,
    chassis: "Freightliner XCR Tag / Spartan K2 Tag",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "Ventana 43-ft class — OEM L9 400/1250",
  },
  {
    yearMin: 2019,
    yearEnd: 2023,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "4310",
    engine: "Cummins L9 400HP",
    horsepower: 400,
    torqueLbFt: 1250,
    chassis: "Freightliner XCR Tag / Spartan K2 Tag",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "Ventana 43-ft class — OEM L9 400/1250",
  },
  {
    yearMin: 2020,
    yearEnd: 2023,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "3436",
    engine: "Cummins B6.7 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner XCR / Spartan K2",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "Ventana 34-ft class — OEM B6.7 360/800 (not L9)",
  },
  {
    yearMin: 2019,
    yearEnd: 2023,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "3717",
    engine: "Cummins B6.7 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner XCR / Spartan K2",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "Ventana 37-ft class — OEM B6.7 360/800",
  },
  {
    yearMin: 2019,
    yearEnd: 2022,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "3426",
    engine: "Cummins B6.7 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner XCR / Spartan K2",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM MY21–22 Ventana 34' 3426: B6.7 360/800",
  },
  {
    yearMin: 2019,
    yearEnd: 2022,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "4002",
    engine: "Cummins L9 400HP",
    horsepower: 400,
    torqueLbFt: 1250,
    chassis: "Freightliner XCR Tag / Spartan K2 Tag",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM MY21–22 Ventana 40' 4002: L9 400/1250",
  },
  {
    yearMin: 2019,
    yearEnd: 2021,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "4311",
    engine: "Cummins L9 400HP",
    horsepower: 400,
    torqueLbFt: 1250,
    chassis: "Freightliner XCR Tag / Spartan K2 Tag",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM MY21 Ventana 43' 4311: L9 400/1250",
  },
  {
    yearMin: 2021,
    yearEnd: 2021,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "4329",
    engine: "Cummins L9 400HP",
    horsepower: 400,
    torqueLbFt: 1250,
    chassis: "Freightliner XCR Tag / Spartan K2 Tag",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM MY21 Ventana 43' 4329: L9 400/1250",
  },
  {
    yearMin: 2021,
    yearEnd: 2021,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "4354",
    engine: "Cummins L9 400HP",
    horsepower: 400,
    torqueLbFt: 1250,
    chassis: "Freightliner XCR Tag / Spartan K2 Tag",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM MY21 Ventana 43' 4354: L9 400/1250",
  },
  {
    yearMin: 2020,
    yearEnd: 2021,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "4362",
    engine: "Cummins L9 400HP",
    horsepower: 400,
    torqueLbFt: 1250,
    chassis: "Freightliner XCR Tag / Spartan K2 Tag",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM MY20–21 Ventana 43' 4362: L9 400/1250 (not in MY19 brochure)",
  },
  {
    yearMin: 2019,
    yearEnd: 2020,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "4054",
    engine: "Cummins L9 400HP",
    horsepower: 400,
    torqueLbFt: 1250,
    chassis: "Freightliner XCR Tag / Spartan K2 Tag",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM MY19–20 Ventana 40' 4054: ISL/L9 400 — not in MY21+ Ventana chassis tables",
  },
  {
    yearMin: 2019,
    yearEnd: 2020,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "4348",
    engine: "Cummins L9 400HP",
    horsepower: 400,
    torqueLbFt: 1250,
    chassis: "Freightliner XCR Tag / Spartan K2 Tag",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM MY19–20 Ventana 43' 4348: ISL/L9 400 — not in MY21+ Ventana chassis tables",
  },
  {
    yearMin: 2019,
    yearEnd: 2023,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "3407",
    engine: "Cummins B6.7 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner XCR / Spartan K2",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "Ventana 34-ft class — OEM B6.7 360/800",
  },
  {
    yearMin: 2019,
    yearEnd: 2023,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "3412",
    engine: "Cummins B6.7 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner XCR / Spartan K2",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "Ventana 34-ft class — OEM B6.7 360/800",
  },
  {
    yearMin: 2019,
    yearEnd: 2023,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "3709",
    engine: "Cummins B6.7 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner XCR / Spartan K2",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "Ventana 37-ft class — OEM B6.7 360/800",
  },
  {
    yearMin: 2020,
    yearEnd: 2024,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "4068",
    engine: "Cummins L 400HP",
    horsepower: 400,
    torqueLbFt: 1250,
    chassis: "Freightliner XCR Tag / Spartan K2 Tag",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "Ventana 40-ft class — OEM L9/L 400/1250 (MY23 L9, MY24 L)",
  },
  {
    yearMin: 2019,
    yearEnd: 2024,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "4326",
    engine: "Cummins L 400HP",
    horsepower: 400,
    torqueLbFt: 1250,
    chassis: "Freightliner XCR Tag / Spartan K2 Tag",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "Ventana 43-ft class — OEM L9/L 400/1250",
  },
  {
    yearMin: 2020,
    yearEnd: 2024,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "4328",
    engine: "Cummins L 400HP",
    horsepower: 400,
    torqueLbFt: 1250,
    chassis: "Freightliner XCR Tag / Spartan K2 Tag",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "Ventana 43-ft class — OEM L9/L 400/1250",
  },
  {
    yearMin: 2020,
    yearEnd: 2023,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "4334",
    engine: "Cummins L9 400HP",
    horsepower: 400,
    torqueLbFt: 1250,
    chassis: "Freightliner XCR Tag / Spartan K2 Tag",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "Ventana 43-ft 4334 — OEM L9 400/1250 (MY23; not in MY24 brochure)",
  },
  {
    yearMin: 2012,
    yearEnd: 2018,
    makeIncludes: "newmar",
    modelIncludes: "ventana le",
    engine: "Cummins ISB 6.7L 340HP",
    horsepower: 340,
    torqueLbFt: 800,
    chassis: "Freightliner XCR",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "Ventana LE 2012–2018 default — ISB 340/800, not L9 400 and not Ford 7.3. MY17–18 34–37' is 340; 40' is 360. MY19 37–40' is 360.",
  },
  {
    yearMin: 2017,
    yearEnd: 2018,
    makeIncludes: "newmar",
    modelIncludes: "ventana le",
    floorplanIncludes: "3412",
    engine: "Cummins ISB 6.7L 340HP",
    horsepower: 340,
    torqueLbFt: 800,
    chassis: "Freightliner XCR",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM MY17–18 Ventana LE 34' 3412: ISB 340 — not 360",
  },
  {
    yearMin: 2018,
    yearEnd: 2018,
    makeIncludes: "newmar",
    modelIncludes: "ventana le",
    floorplanIncludes: "3413",
    engine: "Cummins ISB 6.7L 340HP",
    horsepower: 340,
    torqueLbFt: 800,
    chassis: "Freightliner XCR",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM 2018_Ventana_LE 34' 3413: ISB 340",
  },
  {
    yearMin: 2017,
    yearEnd: 2018,
    makeIncludes: "newmar",
    modelIncludes: "ventana le",
    floorplanIncludes: "3709",
    engine: "Cummins ISB 6.7L 340HP",
    horsepower: 340,
    torqueLbFt: 800,
    chassis: "Freightliner XCR",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM MY17–18 Ventana LE 37' 3709: ISB 340 — not the MY19 360 rating",
  },
  {
    yearMin: 2018,
    yearEnd: 2018,
    makeIncludes: "newmar",
    modelIncludes: "ventana le",
    floorplanIncludes: "3713",
    engine: "Cummins ISB 6.7L 340HP",
    horsepower: 340,
    torqueLbFt: 800,
    chassis: "Freightliner XCR",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM 2018_Ventana_LE 37' 3713: ISB 340",
  },
  {
    yearMin: 2017,
    yearEnd: 2017,
    makeIncludes: "newmar",
    modelIncludes: "ventana le",
    floorplanIncludes: "3724",
    engine: "Cummins ISB 6.7L 340HP",
    horsepower: 340,
    torqueLbFt: 800,
    chassis: "Freightliner XCR",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM 2017_Ventana_LE 37' 3724: ISB 340",
  },
  {
    yearMin: 2017,
    yearEnd: 2018,
    makeIncludes: "newmar",
    modelIncludes: "ventana le",
    floorplanIncludes: "4042",
    engine: "Cummins ISB 6.7L 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner XCR",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM MY17–18 Ventana LE 40' 4042: ISB 360",
  },
  {
    yearMin: 2017,
    yearEnd: 2017,
    makeIncludes: "newmar",
    modelIncludes: "ventana le",
    floorplanIncludes: "4044",
    engine: "Cummins ISB 6.7L 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner XCR",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM 2017_Ventana_LE 40' 4044: ISB 360",
  },
  {
    yearMin: 2018,
    yearEnd: 2018,
    makeIncludes: "newmar",
    modelIncludes: "ventana le",
    floorplanIncludes: "4048",
    engine: "Cummins ISB 6.7L 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner XCR",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM 2018_Ventana_LE 40' 4048: ISB 360",
  },
  {
    yearMin: 2012,
    yearEnd: 2019,
    makeIncludes: "newmar",
    modelIncludes: "ventana le",
    floorplanIncludes: "4037",
    engine: "Cummins ISB 6.7L 360HP",
    horsepower: 360,
    torqueLbFt: 1000,
    chassis: "Freightliner XCR",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "Ventana LE 40-ft — ISB 360",
  },
  {
    yearMin: 2012,
    yearEnd: 2019,
    makeIncludes: "newmar",
    modelIncludes: "ventana le",
    floorplanIncludes: "4002",
    engine: "Cummins ISB 6.7L 360HP",
    horsepower: 360,
    torqueLbFt: 1000,
    chassis: "Freightliner XCR",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "Ventana LE 40-ft — ISB 360",
  },
  {
    yearMin: 2019,
    yearEnd: 2019,
    makeIncludes: "newmar",
    modelIncludes: "ventana le",
    floorplanIncludes: "3412",
    engine: "Cummins ISB 6.7L 340HP",
    horsepower: 340,
    torqueLbFt: 800,
    chassis: "Freightliner XCR",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM 2019_Ventana_LE 34' 3412: ISB 340 — not 360",
  },
  {
    yearMin: 2019,
    yearEnd: 2019,
    makeIncludes: "newmar",
    modelIncludes: "ventana le",
    floorplanIncludes: "3426",
    engine: "Cummins ISB 6.7L 340HP",
    horsepower: 340,
    torqueLbFt: 800,
    chassis: "Freightliner XCR",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM 2019_Ventana_LE 34' 3426: ISB 340 — not 360",
  },
  {
    yearMin: 2019,
    yearEnd: 2019,
    makeIncludes: "newmar",
    modelIncludes: "ventana le",
    floorplanIncludes: "3709",
    engine: "Cummins ISB 6.7L 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner XCR",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM 2019_Ventana_LE 37' 3709: ISB 360 — not 340 (2012–2018 short-band)",
  },
  {
    yearMin: 2019,
    yearEnd: 2019,
    makeIncludes: "newmar",
    modelIncludes: "ventana le",
    floorplanIncludes: "3717",
    engine: "Cummins ISB 6.7L 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner XCR",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM 2019_Ventana_LE 37' 3717: ISB 360",
  },
  {
    yearMin: 2019,
    yearEnd: 2019,
    makeIncludes: "newmar",
    modelIncludes: "ventana le",
    floorplanIncludes: "4045",
    engine: "Cummins ISB 6.7L 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner XCR",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM 2019_Ventana_LE 40' 4045: ISB 360",
  },
  {
    yearMin: 2019,
    yearEnd: 2019,
    makeIncludes: "newmar",
    modelIncludes: "ventana le",
    floorplanIncludes: "4048",
    engine: "Cummins ISB 6.7L 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner XCR",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM 2019_Ventana_LE 40' 4048: ISB 360",
  },
  {
    yearMin: 2019,
    yearEnd: 2019,
    makeIncludes: "newmar",
    modelIncludes: "ventana le",
    engine: "Cummins ISB 6.7L 340–360HP (by length)",
    horsepower: 340,
    torqueLbFt: 800,
    chassis: "Freightliner XCR",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM 2019_Ventana_LE final year: 34' 340 / 37–40' 360. Up to 360 HP. No 2020 brochure.",
  },
  // NO model-wide Ventana pin that forces 360 on every plan
  {
    yearMin: 2021,
    yearEnd: 2021,
    makeIncludes: "newmar",
    modelIncludes: "new aire",
    floorplanIncludes: "3341",
    engine: "Cummins B6.7 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM 2021_New_Aire 33' 3341: Freightliner 360 — not L9 450",
  },
  {
    yearMin: 2021,
    yearEnd: 2021,
    makeIncludes: "newmar",
    modelIncludes: "new aire",
    floorplanIncludes: "3343",
    engine: "Cummins B6.7 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM 2021_New_Aire 33' 3343: Freightliner 360 — not L9 450",
  },
  {
    yearMin: 2021,
    yearEnd: 2027,
    makeIncludes: "newmar",
    modelIncludes: "new aire",
    engine: "Cummins L9 450HP",
    horsepower: 450,
    torqueLbFt: 1250,
    chassis: "Freightliner / Spartan K2 (by option)",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM MY21 35' / MY22–27 New Aire — L9 450/1250 (not B6.7 360). MY21 33' is 360.",
  },
  {
    yearMin: 2014,
    yearEnd: 2016,
    makeIncludes: "newmar",
    modelIncludes: "new aire",
    engine: "Cummins B6.7 / ISB 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner XCS",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "Pre-modern New Aire keys left for later slices. No OEM MY17 brochure — do not stamp 2017.",
  },
  {
    yearMin: 2018,
    yearEnd: 2019,
    makeIncludes: "newmar",
    modelIncludes: "new aire",
    engine: "Cummins B6.7 / ISB 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner XCS",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM 2018_New_Aire is 3341/3343 360 only. OEM 2019_New_Aire is 33' 360 only (no 35'). No OEM MY17 brochure.",
  },
  {
    yearMin: 2020,
    yearEnd: 2020,
    makeIncludes: "newmar",
    modelIncludes: "new aire",
    floorplanIncludes: "3341",
    engine: "Cummins B6.7 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM 2020_New_Aire 33' 3341: Freightliner 360 — not L9 450",
  },
  {
    yearMin: 2020,
    yearEnd: 2020,
    makeIncludes: "newmar",
    modelIncludes: "new aire",
    floorplanIncludes: "3343",
    engine: "Cummins B6.7 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM 2020_New_Aire 33' 3343: Freightliner 360 — not L9 450",
  },
  {
    yearMin: 2020,
    yearEnd: 2020,
    makeIncludes: "newmar",
    modelIncludes: "new aire",
    floorplanIncludes: "3345",
    engine: "Cummins B6.7 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM 2020_New_Aire 33' 3345: Freightliner 360 — not L9 450",
  },
  {
    yearMin: 2020,
    yearEnd: 2020,
    makeIncludes: "newmar",
    modelIncludes: "new aire",
    engine: "Cummins L9 450HP",
    horsepower: 450,
    torqueLbFt: 1250,
    chassis: "Freightliner",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM 2020_New_Aire 35' default L9 450. 33' 3341/3343/3345 are 360.",
  },
  // Fleetwood Bounder / Southwind gas V10 era
  {
    yearMin: 2005,
    yearEnd: 2015,
    makeIncludes: "fleetwood",
    modelIncludes: "bounder",
    engine: "Ford Triton V10 6.8L",
    horsepower: 320,
    chassis: "Ford F53",
    fuelType: "Gas",
    note: "2005–2015 Bounder — V10 era (not 7.3 Godzilla)",
  },
  {
    yearMin: 2005,
    yearEnd: 2015,
    makeIncludes: "fleetwood",
    modelIncludes: "southwind",
    engine: "Ford Triton V10 6.8L",
    horsepower: 320,
    chassis: "Ford F53",
    fuelType: "Gas",
    note: "2005–2015 gas Class A — Triton V10",
  },
  {
    yearMin: 2005,
    yearEnd: 2015,
    makeIncludes: "tiffin",
    modelIncludes: "allegro bus",
    engine: "Cummins ISL / ISB diesel (era)",
    horsepower: 380,
    chassis: "Freightliner / PowerGlide (by year)",
    fuelType: "Diesel",
    note: "2005–2015 Allegro Bus — confirm ISL rating on build sheet",
  },
  {
    yearMin: 2005,
    yearEnd: 2015,
    makeIncludes: "tiffin",
    modelIncludes: "phaeton",
    engine: "Cummins ISL / ISB diesel (era)",
    horsepower: 380,
    chassis: "Freightliner / PowerGlide (by year)",
    fuelType: "Diesel",
  },
  {
    yearMin: 2005,
    yearEnd: 2015,
    makeIncludes: "tiffin",
    modelIncludes: "allegro open road",
    engine: "Ford 6.8L V10 / E-450 (era)",
    horsepower: 305,
    chassis: "Ford F53 / E-450",
    fuelType: "Gas",
  },
  {
    yearMin: 2016,
    yearEnd: 2026,
    makeIncludes: "dynamax",
    modelIncludes: "isata 3",
    engine: "Mercedes-Benz 2.0L I4 turbodiesel",
    horsepower: 211,
    chassis: "Mercedes-Benz Sprinter",
    fuelType: "Diesel",
    note: "Isata 3 — Sprinter diesel (team catalog corrected)",
  },
  // Discovery modern pin (duplicate-safe longer window)
  {
    yearMin: 2015,
    yearEnd: 2026,
    makeIncludes: "fleetwood",
    modelIncludes: "discovery",
    engine: "Cummins B6.7 (ISB) 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner XC-Series",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "Regular Discovery — not LXE / not ISL 8.9",
  },
  {
    yearMin: 2025,
    yearEnd: 2027,
    makeIncludes: "fleetwood",
    modelIncludes: "altitude",
    engine: "Ford 7.3L V8 325HP",
    horsepower: 325,
    torqueLbFt: 450,
    chassis: "Ford E-450",
    transmission: "Electronic 6-speed automatic",
    fuelType: "Gas",
    note: "Altitude Class C E-450 brochure: 325 HP / 450 lb-ft — not F53 335/468. Tires LT225/75R16E. Onan 4000W Quiet gas std.",
  },
  {
    yearMin: 2025,
    yearEnd: 2026,
    makeIncludes: "fleetwood",
    modelIncludes: "insight",
    engine: "Mercedes-Benz 2.0L 4-cyl turbo diesel 211HP",
    horsepower: 211,
    torqueLbFt: 332,
    chassis: "Mercedes-Benz Sprinter 3500XD",
    transmission: "9-speed automatic",
    fuelType: "Diesel",
    note: "Insight MY26 sales sheet: 211/332 Sprinter 3500XD. Tires LT215/85SR16. 3.6 kW LP gen. Not E-450.",
  },
  {
    yearMin: 2026,
    yearEnd: 2027,
    makeIncludes: "fleetwood",
    modelIncludes: "altitude fs550",
    engine: "Ford 7.3L V8 335HP",
    horsepower: 335,
    torqueLbFt: 468,
    chassis: "Ford F-550 (4x2 or 4x4)",
    fuelType: "Gas",
    note: "Altitude FS550 Super C — F-550 335/468. Not E-450 Altitude.",
  },
  {
    yearMin: 2026,
    yearEnd: 2027,
    makeIncludes: "fleetwood",
    modelIncludes: "altitude fs600d",
    engine: "Ford 6.7L Power Stroke 330HP",
    horsepower: 330,
    torqueLbFt: 950,
    chassis: "Ford F-600 4x4",
    transmission: "10-speed automatic",
    fuelType: "Diesel",
    note: "Altitude FS600D Super C diesel — F-600 4x4 330/950.",
  },
  {
    yearMin: 2020,
    yearEnd: 2020,
    makeIncludes: "fleetwood",
    modelIncludes: "fortis",
    engine: "Ford Triton V10 6.8L 320HP",
    horsepower: 320,
    torqueLbFt: 460,
    chassis: "Ford F53",
    transmission: "Ford 6-speed automatic",
    fuelType: "Gas",
    note: "Fortis MY20 brochure: 6.8L Triton V10 320/460. Plans 33HB / 34MB only. Onan 5.5 kW Quiet. Not 7.3.",
  },
  {
    yearMin: 2021,
    yearEnd: 2023,
    makeIncludes: "fleetwood",
    modelIncludes: "fortis",
    engine: "Ford 7.3L V8 350HP",
    horsepower: 350,
    torqueLbFt: 468,
    chassis: "Ford F53",
    transmission: "Ford 6-speed automatic",
    fuelType: "Gas",
    note: "Fortis MY21 brochure / MY22 sheets / OEM 2023: F53 7.3 350 HP / 468 lb-ft (pre-MY24 335 recert). MY21–22 plans 32RW / 33HB / 34MB / 36DB.",
  },
  {
    yearMin: 2024,
    yearEnd: 2027,
    makeIncludes: "fleetwood",
    modelIncludes: "fortis",
    engine: "Ford 7.3L V8 335HP",
    horsepower: 335,
    torqueLbFt: 468,
    chassis: "Ford F53",
    transmission: "Ford 6-speed automatic",
    fuelType: "Gas",
    note: "FORTIS24F1 / MY26 sales sheet: F53 7.3 335 HP / 468 lb-ft (not marketing 350).",
  },
  {
    yearMin: 2017,
    yearEnd: 2018,
    makeIncludes: "fleetwood",
    modelIncludes: "bounder",
    engine: "Ford Triton V10 6.8L 320HP",
    horsepower: 320,
    torqueLbFt: 460,
    chassis: "Ford F53",
    fuelType: "Gas",
    note: "BOUNDER18B1 / RVUSA 2017 Bounder: 6.8L Triton V10 320/460. MY17 33C/34T/35K/35P/36H; MY18 33C/35K/35P/36H. Not 7.3. Do not invent gen kW.",
  },
  {
    yearMin: 2019,
    yearEnd: 2020,
    makeIncludes: "fleetwood",
    modelIncludes: "bounder",
    engine: "Ford Triton V10 6.8L 320HP",
    horsepower: 320,
    torqueLbFt: 460,
    chassis: "Ford F53",
    fuelType: "Gas",
    note: "Bounder MY19/MY20 brochures: 6.8L Triton V10 320/460. Plans 33C/35K/35P/36F/36FP. Onan 5.5 kW gas. Not 7.3.",
  },
  {
    yearMin: 2021,
    yearEnd: 2022,
    makeIncludes: "fleetwood",
    modelIncludes: "bounder",
    engine: "Ford 7.3L V8 350HP",
    horsepower: 350,
    torqueLbFt: 468,
    chassis: "Ford F53",
    fuelType: "Gas",
    note: "Bounder MY21/MY22 brochures: F53 7.3 350/468. MY21 33C/35K/35P/36F; MY22 33C/35GL/35K/36F. Onan 5.5 kW gas.",
  },
  {
    yearMin: 2023,
    yearEnd: 2023,
    makeIncludes: "fleetwood",
    modelIncludes: "bounder",
    engine: "Ford 7.3L V8 350HP",
    horsepower: 350,
    torqueLbFt: 468,
    chassis: "Ford F53",
    fuelType: "Gas",
    note: "BOUNDER23F1 / OEM 2023 Bounder: F53 7.3 350/468. Plans 33C / 35GL / 35K / 36F.",
  },
  {
    yearMin: 2024,
    yearEnd: 2026,
    makeIncludes: "fleetwood",
    modelIncludes: "bounder",
    engine: "Ford 7.3L V8 335HP",
    horsepower: 335,
    torqueLbFt: 468,
    chassis: "Ford F53",
    fuelType: "Gas",
    note: "BOUNDER24F1 / MY26 sheet: F53 7.3 335/468. Plans 33C / 35GL / 35K / 36F.",
  },
  {
    yearMin: 2023,
    yearEnd: 2023,
    makeIncludes: "fleetwood",
    modelIncludes: "flex",
    engine: "Ford 7.3L V8 350HP",
    horsepower: 350,
    torqueLbFt: 468,
    chassis: "Ford F53",
    fuelType: "Gas",
    note: "FLEX23F1: 350 HP @ 3,900 / 468 lb-ft. Plans 32S / 34J / 35R.",
  },
  {
    yearMin: 2024,
    yearEnd: 2025,
    makeIncludes: "fleetwood",
    modelIncludes: "flex",
    engine: "Ford 7.3L V8 335HP",
    horsepower: 335,
    torqueLbFt: 468,
    chassis: "Ford F53",
    fuelType: "Gas",
    note: "FLEX24F1: 335 HP / 468 lb-ft. Plans 32S / 34J / 35R.",
  },
  {
    yearMin: 2017,
    yearEnd: 2018,
    makeIncludes: "fleetwood",
    modelIncludes: "flair",
    engine: "Ford Triton V10 6.8L 320HP",
    horsepower: 320,
    torqueLbFt: 460,
    chassis: "Ford F53",
    fuelType: "Gas",
    note: "FLR17F1 / FLRFLRLXE18B1: 6.8L Triton V10 320/460. MY17 26D/30P/31A/31E; MY18 30P/31A/31E. Gen 4.0 std / 5.5 opt — do not invent a single kW.",
  },
  {
    yearMin: 2019,
    yearEnd: 2020,
    makeIncludes: "fleetwood",
    modelIncludes: "flair",
    engine: "Ford Triton V10 6.8L 320HP",
    horsepower: 320,
    torqueLbFt: 460,
    chassis: "Ford F53",
    fuelType: "Gas",
    note: "Flair MY19/MY20 brochures: 6.8L Triton V10 320/460. Plans 28A / 29M / 32S / 34J / 35R. Gen kW varies — do not invent a single kW.",
  },
  {
    yearMin: 2021,
    yearEnd: 2023,
    makeIncludes: "fleetwood",
    modelIncludes: "flair",
    engine: "Ford 7.3L V8 350HP",
    horsepower: 350,
    torqueLbFt: 468,
    chassis: "Ford F53",
    fuelType: "Gas",
    note: "Flair MY21/MY22 brochures: 350/468. MY21–22 plans 28A / 29M / 32S / 34J / 35R. MY23: 28A / 29M / 32N / 33B6.",
  },
  {
    yearMin: 2024,
    yearEnd: 2026,
    makeIncludes: "fleetwood",
    modelIncludes: "flair",
    engine: "Ford 7.3L V8 335HP",
    horsepower: 335,
    torqueLbFt: 468,
    chassis: "Ford F53",
    fuelType: "Gas",
    note: "FLAIR24F1: 335 HP / 468 lb-ft. MY24–25 plans 28A / 29M / 32N / 33B6.",
  },
  {
    yearMin: 2022,
    yearEnd: 2026,
    makeIncludes: "fleetwood",
    modelIncludes: "frontier",
    engine: "Cummins diesel 340HP",
    horsepower: 340,
    torqueLbFt: 700,
    chassis: "Freightliner Custom Chassis XCR",
    fuelType: "Diesel",
    note: "OEM debut MY22–25 Frontier: 34GT / 36SS, 340 HP / 700 lb-ft XCR. No 2021 Frontier. Bare frontier must not stamp GTX.",
  },
  {
    yearMin: 2023,
    yearEnd: 2025,
    makeIncludes: "fleetwood",
    modelIncludes: "frontier gtx",
    engine: "Cummins B6.7 360HP",
    horsepower: 360,
    torqueLbFt: 800,
    chassis: "Freightliner Custom Chassis XCR",
    transmission: "Allison 3000 MH 6-speed",
    fuelType: "Diesel",
    note: "GTX24F1 / OEM 2023–25: 37RT / 39TA, Cummins 6.7 360/800.",
  },
  {
    yearMin: 2017,
    yearEnd: 2023,
    makeIncludes: "fleetwood",
    modelIncludes: "pace arrow",
    engine: "Cummins ISB 6.7 300HP / 340HP (by floorplan)",
    horsepower: 0,
    chassis: "Freightliner XCS",
    fuelType: "Diesel",
    note: "MY17–23 Pace Arrow is diesel, not F53 gas. 33D = 300/660 Allison 2100; 35E/35M/35QS/35RB/35S/35BP/36U = 340/700 Allison 2500.",
  },
  {
    yearMin: 2017,
    yearEnd: 2023,
    makeIncludes: "fleetwood",
    modelIncludes: "pace arrow",
    floorplanIncludes: "33D",
    engine: "Cummins ISB 6.7 300HP",
    horsepower: 300,
    torqueLbFt: 660,
    chassis: "Freightliner XCS",
    transmission: "Allison 2100 MH 6-speed",
    fuelType: "Diesel",
    note: "Pace Arrow MY17–23 33D — 300 HP / 660 lb-ft.",
  },
  {
    yearMin: 2017,
    yearEnd: 2019,
    makeIncludes: "fleetwood",
    modelIncludes: "pace arrow",
    floorplanIncludes: "35E",
    engine: "Cummins ISB 6.7 340HP",
    horsepower: 340,
    torqueLbFt: 700,
    chassis: "Freightliner XCS",
    transmission: "Allison 2500 MH 6-speed",
    fuelType: "Diesel",
    note: "Pace Arrow MY17–19 35E — 340 HP / 700 lb-ft. Dropped MY20.",
  },
  {
    yearMin: 2017,
    yearEnd: 2018,
    makeIncludes: "fleetwood",
    modelIncludes: "pace arrow",
    floorplanIncludes: "35M",
    engine: "Cummins ISB 6.7 340HP",
    horsepower: 340,
    torqueLbFt: 700,
    chassis: "Freightliner XCS",
    transmission: "Allison 2500 MH 6-speed",
    fuelType: "Diesel",
    note: "PAPALXE17B1 / 2018 Pace Arrow 35M — 340 HP / 700 lb-ft. Dropped MY19.",
  },
  {
    yearMin: 2019,
    yearEnd: 2021,
    makeIncludes: "fleetwood",
    modelIncludes: "pace arrow",
    floorplanIncludes: "35QS",
    engine: "Cummins ISB 6.7 340HP",
    horsepower: 340,
    torqueLbFt: 700,
    chassis: "Freightliner XCS",
    transmission: "Allison 2500 MH 6-speed",
    fuelType: "Diesel",
    note: "Pace Arrow MY19–21 35QS — 340 HP / 700 lb-ft. Dropped MY22.",
  },
  {
    yearMin: 2020,
    yearEnd: 2021,
    makeIncludes: "fleetwood",
    modelIncludes: "pace arrow",
    floorplanIncludes: "35RB",
    engine: "Cummins ISB 6.7 340HP",
    horsepower: 340,
    torqueLbFt: 700,
    chassis: "Freightliner XCS",
    transmission: "Allison 2500 MH 6-speed",
    fuelType: "Diesel",
    note: "Pace Arrow MY20–21 35RB — 340 HP / 700 lb-ft. Dropped MY22.",
  },
  {
    yearMin: 2020,
    yearEnd: 2021,
    makeIncludes: "fleetwood",
    modelIncludes: "pace arrow",
    floorplanIncludes: "35S",
    engine: "Cummins ISB 6.7 340HP",
    horsepower: 340,
    torqueLbFt: 700,
    chassis: "Freightliner XCS",
    transmission: "Allison 2500 MH 6-speed",
    fuelType: "Diesel",
    note: "Pace Arrow MY20–21 35S — 340 HP / 700 lb-ft. Dropped MY22.",
  },
  {
    yearMin: 2023,
    yearEnd: 2023,
    makeIncludes: "fleetwood",
    modelIncludes: "pace arrow",
    floorplanIncludes: "35BP",
    engine: "Cummins ISB 6.7 340HP",
    horsepower: 340,
    torqueLbFt: 700,
    chassis: "Freightliner XCS",
    transmission: "Allison 2100 MH 6-speed",
    fuelType: "Diesel",
    note: "PACEARROW23F1 35BP — 340 HP / 700 lb-ft.",
  },
  {
    yearMin: 2017,
    yearEnd: 2022,
    makeIncludes: "fleetwood",
    modelIncludes: "pace arrow",
    floorplanIncludes: "36U",
    engine: "Cummins ISB 6.7 340HP",
    horsepower: 340,
    torqueLbFt: 700,
    chassis: "Freightliner XCS",
    transmission: "Allison 2500 MH 6-speed",
    fuelType: "Diesel",
    note: "Pace Arrow MY17–22 36U — 340 HP / 700 lb-ft, Allison 2500.",
  },
  {
    yearMin: 2023,
    yearEnd: 2023,
    makeIncludes: "fleetwood",
    modelIncludes: "pace arrow",
    floorplanIncludes: "36U",
    engine: "Cummins ISB 6.7 340HP",
    horsepower: 340,
    torqueLbFt: 700,
    chassis: "Freightliner XCS",
    transmission: "Allison 2100 MH 6-speed",
    fuelType: "Diesel",
    note: "PACEARROW23F1 36U — 340 HP / 700 lb-ft.",
  },
  {
    yearMin: 2017,
    yearEnd: 2018,
    makeIncludes: "fleetwood",
    modelIncludes: "southwind",
    engine: "Ford Triton V10 6.8L 320HP",
    horsepower: 320,
    torqueLbFt: 460,
    chassis: "Ford F53",
    fuelType: "Gas",
    note: "SW17F1 / SW18B1: 6.8L Triton V10 320/460. MY17 32VS/34A/36L; MY18 34C/35K/36P/37H. Not 7.3. Do not invent gen kW.",
  },
  {
    yearMin: 2019,
    yearEnd: 2020,
    makeIncludes: "fleetwood",
    modelIncludes: "southwind",
    engine: "Ford Triton V10 6.8L 320HP",
    horsepower: 320,
    torqueLbFt: 460,
    chassis: "Ford F53",
    fuelType: "Gas",
    note: "Southwind MY19/MY20 brochures: 6.8L Triton V10 320/460. Plans 34C/35K/36P/37F/37FP. Onan 5.5 kW std. Not 7.3.",
  },
  {
    yearMin: 2017,
    yearEnd: 2018,
    makeIncludes: "fleetwood",
    modelIncludes: "storm",
    engine: "Ford Triton V10 6.8L 320HP",
    horsepower: 320,
    torqueLbFt: 460,
    chassis: "Ford F53",
    fuelType: "Gas",
    note: "ST17B1 / 2018 Storm brochure: 6.8L Triton V10 320. Plans 32A/34S/36D/36F. Final MY 2018. Do not invent gen kW.",
  },
  {
    yearMin: 2018,
    yearEnd: 2019,
    makeIncludes: "fleetwood",
    modelIncludes: "pulse",
    engine: "Mercedes-Benz 3.0L V6 turbodiesel 188HP",
    horsepower: 188,
    torqueLbFt: 260,
    chassis: "Mercedes-Benz Sprinter",
    transmission: "Mercedes-Benz 5-Speed Automatic",
    fuelType: "Diesel",
    note: "PULSE18B1: Sprinter 3.0 188/260. MY18 24A/24B/24C/24D; MY19 24A/24B. No 2017 OEM page.",
  },
  {
    yearMin: 2021,
    yearEnd: 2023,
    makeIncludes: "fleetwood",
    modelIncludes: "southwind",
    engine: "Ford 7.3L V8 350HP",
    horsepower: 350,
    torqueLbFt: 468,
    chassis: "Ford F53",
    fuelType: "Gas",
    note: "Southwind MY21 brochure / MY22 brochure / sibling MY23 F53 7.3: 350/468. MY21 34C/35K/36P/37F; MY22–23 34C/35K/36GL/37F. Onan 5.5 kW gas std.",
  },
  {
    yearMin: 2024,
    yearEnd: 2024,
    makeIncludes: "fleetwood",
    modelIncludes: "xcursion",
    engine: "Mercedes-Benz 2.0L I4 turbodiesel 211HP",
    horsepower: 211,
    torqueLbFt: 332,
    chassis: "Mercedes-Benz Sprinter 2500 / 3500",
    transmission: "9-speed automatic",
    fuelType: "Diesel",
    note: "2024 Xcursion brochure: 211/332 Sprinter. Plans AL2 / SL2 / SL2E / SL4E. Optional gen — do not invent diesel-or-gas.",
  },
  {
    yearMin: 2013,
    yearEnd: 2021,
    makeIncludes: "winnebago",
    modelIncludes: "via",
    engine: "Mercedes-Benz OM642 3.0L V6 turbodiesel",
    horsepower: 188,
    torqueLbFt: 325,
    chassis: "Mercedes-Benz Sprinter 3500 cowl",
    transmission: "5-speed automatic",
    fuelType: "Diesel",
    note: "Via 25P/25T — Sprinter OM642 188/325. Never Cummins ISL/ISB pusher.",
  },
  {
    yearMin: 2014,
    yearEnd: 2021,
    makeIncludes: "renegade",
    modelIncludes: "villagio",
    engine: "Mercedes-Benz OM642 3.0L V6 turbodiesel",
    horsepower: 188,
    torqueLbFt: 325,
    chassis: "Mercedes-Benz Sprinter 3500 cowl",
    fuelType: "Diesel",
    note: "Villagio Sprinter cowl OM642 — not a Cummins pusher.",
  },
  // ── Newmar MY25–27 OEM DigiBrochure pins ────────────────────────────────
  {
    yearMin: 2017,
    yearEnd: 2017,
    makeIncludes: "newmar",
    modelIncludes: "essex",
    engine: "Cummins ISX 600HP",
    horsepower: 600,
    chassis: "Freightliner SL Tag / Spartan K3 (by option)",
    fuelType: "Diesel",
    note: "OEM 2017_Essex: Freightliner SL or Spartan K3 Passive Steer tag, ISX 600 — not X15 605.",
  },
  {
    yearMin: 2018,
    yearEnd: 2027,
    makeIncludes: "newmar",
    modelIncludes: "essex",
    engine: "Cummins X15 605HP",
    horsepower: 605,
    torqueLbFt: 1950,
    chassis: "Freightliner SL Tag / Spartan K3 (by option)",
    transmission: "Allison 4000 MH",
    fuelType: "Diesel",
    note: "OEM MY18–27 Essex: X15 605. MY18–19 Freightliner SL or Spartan K3; MY20–23 Spartan K3 Tag; later years option-band chassis.",
  },
  {
    yearMin: 2017,
    yearEnd: 2017,
    makeIncludes: "newmar",
    modelIncludes: "king aire",
    engine: "Cummins ISX 600HP",
    horsepower: 600,
    chassis: "Spartan K3",
    fuelType: "Diesel",
    note: "OEM 2017_King_Aire: Spartan K3 tag ISX 600 — not X15 605.",
  },
  {
    yearMin: 2018,
    yearEnd: 2027,
    makeIncludes: "newmar",
    modelIncludes: "king aire",
    engine: "Cummins X15 605HP",
    horsepower: 605,
    torqueLbFt: 1950,
    chassis: "Spartan K3 Tag",
    transmission: "Allison 4000 MH",
    fuelType: "Diesel",
    note: "OEM MY18–27 King Aire: Spartan K3 Tag 605 HP; 12.5 kW Onan; 3×15k HP A/C",
  },
  {
    yearMin: 2017,
    yearEnd: 2017,
    makeIncludes: "newmar",
    modelIncludes: "london aire",
    engine: "Cummins ISX 600HP",
    horsepower: 600,
    chassis: "Freightliner SL Tag / Spartan K3 (by option)",
    fuelType: "Diesel",
    note: "OEM 2017_London_Aire: Freightliner SL or Spartan K3 tag, ISX 600 — not X15 605.",
  },
  {
    yearMin: 2018,
    yearEnd: 2027,
    makeIncludes: "newmar",
    modelIncludes: "london aire",
    engine: "Cummins X15 605HP",
    horsepower: 605,
    torqueLbFt: 1950,
    chassis: "Freightliner SL Tag / Spartan K3 (by option)",
    transmission: "Allison 4000 MH",
    fuelType: "Diesel",
    note: "OEM MY18–27 London Aire: active line, 605 HP on Freightliner SL or Spartan K3 Tag — do not yearEnd.",
  },
  {
    yearMin: 2017,
    yearEnd: 2017,
    makeIncludes: "newmar",
    modelIncludes: "mountain aire",
    engine: "Cummins ISX 500HP",
    horsepower: 500,
    chassis: "Freightliner SL Tag / Spartan K3 (by option)",
    fuelType: "Diesel",
    note: "OEM 2017_Mountain_Aire: Freightliner SL or Spartan K3 Passive Steer tag, ISX 500 — not L9 450, not the later 525.",
  },
  {
    yearMin: 2018,
    yearEnd: 2018,
    makeIncludes: "newmar",
    modelIncludes: "mountain aire",
    engine: "Cummins diesel 500HP",
    horsepower: 500,
    chassis: "Freightliner Tag / Spartan K3 Tag (by option)",
    fuelType: "Diesel",
    note: "OEM 2018_Mountain_Aire: 500 HP on Freightliner or Spartan K3 tag. Brochure does not name ISX vs X12 — not L9 450, not the later 525.",
  },
  {
    yearMin: 2019,
    yearEnd: 2020,
    makeIncludes: "newmar",
    modelIncludes: "mountain aire",
    engine: "Cummins X12 500HP",
    horsepower: 500,
    torqueLbFt: 1695,
    chassis: "Freightliner SL Tag / Spartan K3 (by option)",
    transmission: "Allison 4000 MH",
    fuelType: "Diesel",
    note: "OEM MY19–20 Mountain Aire: X12 500 / 1,695 — not L9 450, not the later 525. Freightliner SL or Spartan K3.",
  },
  {
    yearMin: 2021,
    yearEnd: 2023,
    makeIncludes: "newmar",
    modelIncludes: "mountain aire",
    engine: "Cummins X12 500HP",
    horsepower: 500,
    torqueLbFt: 1695,
    chassis: "Spartan K3 Tag",
    transmission: "Allison 4000 MH",
    fuelType: "Diesel",
    note: "OEM MY21–23 Mountain Aire: Spartan K3 Tag 500 / 1,695 — not L9 450, not the later 525 rating",
  },
  {
    yearMin: 2024,
    yearEnd: 2027,
    makeIncludes: "newmar",
    modelIncludes: "mountain aire",
    engine: "Cummins X12 525HP",
    horsepower: 525,
    torqueLbFt: 1695,
    chassis: "Spartan K3 Tag",
    transmission: "Allison 4000 MH",
    fuelType: "Diesel",
    note: "OEM MY24–27 Mountain Aire: X12 525 / 1,695 — not L9 450",
  },
  {
    yearMin: 2017,
    yearEnd: 2017,
    makeIncludes: "newmar",
    modelIncludes: "dutch star",
    engine: "Cummins ISL 450HP",
    horsepower: 450,
    chassis: "Freightliner (37') / Freightliner or Spartan tag (40'+)",
    fuelType: "Diesel",
    note: "OEM 2017_Dutch_Star: ISL 450. Freightliner on 37'; Freightliner/Spartan tag on 40'+.",
  },
  {
    yearMin: 2018,
    yearEnd: 2018,
    makeIncludes: "newmar",
    modelIncludes: "dutch star",
    engine: "Cummins L 450HP",
    horsepower: 450,
    chassis: "Freightliner XCR (37') / Freightliner or Spartan tag (40'+)",
    fuelType: "Diesel",
    note: "OEM 2018_Dutch_Star: Cummins L 450. Freightliner XCR on 37'; Freightliner/Spartan tag on 40'+.",
  },
  {
    yearMin: 2019,
    yearEnd: 2027,
    makeIncludes: "newmar",
    modelIncludes: "dutch star",
    engine: "Cummins L9 450HP",
    horsepower: 450,
    torqueLbFt: 1250,
    chassis: "Freightliner XCR / Spartan K2 tag (by length)",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM MY19–27 Dutch Star: 450 HP. Freightliner on 37'; Freightliner/Spartan K2 tag on 40'+.",
  },
  {
    yearMin: 2024,
    yearEnd: 2026,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "3507",
    engine: "Cummins L 380HP",
    horsepower: 380,
    torqueLbFt: 1150,
    chassis: "Freightliner / Spartan (by option)",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM MY24–25 Ventana 35': L 380 / 1,150 — not B6.7 360",
  },
  {
    yearMin: 2024,
    yearEnd: 2026,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "3512",
    engine: "Cummins L 380HP",
    horsepower: 380,
    torqueLbFt: 1150,
    chassis: "Freightliner / Spartan (by option)",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM MY24–26 Ventana 35': L 380 / 1,150 — not B6.7 360",
  },
  {
    yearMin: 2024,
    yearEnd: 2026,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "3809",
    engine: "Cummins L 380HP",
    horsepower: 380,
    torqueLbFt: 1150,
    chassis: "Freightliner / Spartan (by option)",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM MY24–26 Ventana 38': L 380 / 1,150",
  },
  {
    yearMin: 2024,
    yearEnd: 2024,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "3817",
    engine: "Cummins L 380HP",
    horsepower: 380,
    torqueLbFt: 1150,
    chassis: "Freightliner / Spartan (by option)",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM MY24 Ventana 38' 3817: L 380 / 1,150",
  },
  {
    yearMin: 2024,
    yearEnd: 2026,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "4037",
    engine: "Cummins L 400HP",
    horsepower: 400,
    torqueLbFt: 1250,
    chassis: "Freightliner Tag / Spartan Tag (by option)",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM MY24–26 Ventana 40': L 400 / 1,250",
  },
  {
    yearMin: 2024,
    yearEnd: 2026,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "4369",
    engine: "Cummins L 400HP",
    horsepower: 400,
    torqueLbFt: 1250,
    chassis: "Freightliner Tag / Spartan Tag (by option)",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM MY24–26 Ventana 43': L 400 / 1,250",
  },
  {
    yearMin: 2027,
    yearEnd: 2027,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "3512",
    engine: "Cummins B6.7 380HP",
    horsepower: 380,
    torqueLbFt: 1150,
    chassis: "Freightliner / Spartan (by option)",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM MY27VT: B6.7 380 / 1,150 on 35–38'",
  },
  {
    yearMin: 2027,
    yearEnd: 2027,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "3809",
    engine: "Cummins B6.7 380HP",
    horsepower: 380,
    torqueLbFt: 1150,
    chassis: "Freightliner / Spartan (by option)",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM MY27VT: B6.7 380 / 1,150 on 35–38'",
  },
  {
    yearMin: 2027,
    yearEnd: 2027,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "4037",
    engine: "Cummins B6.7 400HP",
    horsepower: 400,
    torqueLbFt: 1250,
    chassis: "Freightliner Tag / Spartan Tag (by option)",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM MY27VT: B6.7 400 / 1,250 on 40–43'",
  },
  {
    yearMin: 2027,
    yearEnd: 2027,
    makeIncludes: "newmar",
    modelIncludes: "ventana",
    floorplanIncludes: "4369",
    engine: "Cummins B6.7 400HP",
    horsepower: 400,
    torqueLbFt: 1250,
    chassis: "Freightliner Tag / Spartan Tag (by option)",
    transmission: "Allison 3000 MH",
    fuelType: "Diesel",
    note: "OEM MY27VT: B6.7 400 / 1,250 on 40–43'",
  },
  {
    yearMin: 2017,
    yearEnd: 2020,
    makeIncludes: "newmar",
    modelIncludes: "canyon star",
    engine: "Ford Triton V10 6.8L 320HP",
    horsepower: 320,
    chassis: "Ford F53",
    transmission: "TorqShift automatic",
    fuelType: "Gas",
    note: "OEM MY17–20 Canyon Star: Gas Motor Coach — F-53 26,000 lb, 320 HP Triton V10. Not FED B6.7 340 (MY21+). Not Super C.",
  },
  {
    yearMin: 2021,
    yearEnd: 2027,
    makeIncludes: "newmar",
    modelIncludes: "canyon star",
    engine: "Cummins B6.7 340HP",
    horsepower: 340,
    torqueLbFt: 700,
    chassis: "Freightliner Custom Chassis front-engine diesel",
    fuelType: "Diesel",
    note: "OEM MY21–27 Canyon Star: FED Class A toy hauler — B6.7 340 / 700. Not Super C. MY21–22 do not include 3947.",
  },
  {
    yearMin: 2020,
    yearEnd: 2023,
    makeIncludes: "newmar",
    modelIncludes: "supreme aire",
    engine: "Detroit DD13 505HP",
    horsepower: 505,
    torqueLbFt: 1850,
    chassis: "Freightliner M2-112",
    fuelType: "Diesel",
    note: "OEM MY20–23 Supreme Aire: M2-112 DD13 505 / 1,850 — not the later 525 rating. MY20 plans 4573/4575/4577.",
  },
  {
    yearMin: 2024,
    yearEnd: 2025,
    makeIncludes: "newmar",
    modelIncludes: "supreme aire",
    engine: "Detroit DD13 525HP",
    horsepower: 525,
    torqueLbFt: 1850,
    chassis: "Freightliner M2-112",
    fuelType: "Diesel",
    note: "OEM MY24–25 Supreme Aire: M2-112 DD13 525 / 1,850",
  },
  {
    yearMin: 2026,
    yearEnd: 2027,
    makeIncludes: "newmar",
    modelIncludes: "supreme aire",
    floorplanIncludes: "3827",
    engine: "Detroit DD13 525HP",
    horsepower: 525,
    torqueLbFt: 1850,
    chassis: "Freightliner Cascadia 116 single axle",
    fuelType: "Diesel",
    note: "OEM MY26–27 Supreme Aire 38–41': Cascadia 116 DD13 525",
  },
  {
    yearMin: 2026,
    yearEnd: 2027,
    makeIncludes: "newmar",
    modelIncludes: "supreme aire",
    floorplanIncludes: "4505",
    engine: "Detroit DD16 600HP",
    horsepower: 600,
    torqueLbFt: 1850,
    chassis: "Freightliner Cascadia 126 tandem axle",
    fuelType: "Diesel",
    note: "OEM MY26–27 Supreme Aire 43–45': Cascadia 126 DD16 600",
  },
  {
    yearMin: 2026,
    yearEnd: 2027,
    makeIncludes: "newmar",
    modelIncludes: "super star",
    floorplanIncludes: "4159",
    engine: "Cummins L 450HP (Freightliner M2-112)",
    horsepower: 450,
    torqueLbFt: 1250,
    chassis: "Freightliner M2-112",
    fuelType: "Diesel",
    note: "Super Star 41 ft M2-112 450",
  },
  {
    yearMin: 2026,
    yearEnd: 2026,
    makeIncludes: "newmar",
    modelIncludes: "super star",
    floorplanIncludes: "4161",
    engine: "Cummins L 450HP (Freightliner M2-112)",
    horsepower: 450,
    torqueLbFt: 1250,
    chassis: "Freightliner M2-112",
    fuelType: "Diesel",
    note: "Super Star 41 ft M2-112 450 (MY26 4161)",
  },
];

/** Patterns that prove a Live Grok narrative stole a flagship/sibling powertrain. */
const FLAGSHIP_ENGINE_RE =
  /\b(isl\s*8\.?9|isl\b|l9\s*450|x15|x12\s*500|1[,.]?250\s*lb|1250\s*lb|450\s*hp)\b/i;
const GAS_V10_RE =
  /\b(triton|v10|6\.8l\s*v10|ford\s*f-?53|torqshift|godzilla)\b/i;
const MID_DIESEL_RE = /\b(isb|b6\.7|b6\.7|340\s*hp|360\s*hp)\b/i;

export function findPowertrainCorrection(
  year: string | number,
  make: string,
  model: string,
  floorplan?: string,
): PowertrainCorrection | null {
  const y = typeof year === "number" ? year : parseInt(String(year), 10);
  if (!Number.isFinite(y)) return null;
  const mk = make.toLowerCase();
  const md = model.toLowerCase().replace(/\s+/g, " ").trim();
  const fp = (floorplan || "").toLowerCase();

  // Prefer floorplan-specific pins, then longer modelIncludes
  const hits = POWERTRAIN_CORRECTIONS.filter((c) => {
    if (y < c.yearMin || y > c.yearEnd) return false;
    if (!mk.includes(c.makeIncludes.toLowerCase())) return false;
    // Bare "newmar" must not stamp live-line pins onto Newmar Classic historic rows
    if (c.makeIncludes === "newmar" && mk.includes("classic")) return false;
    if (!md.includes(c.modelIncludes.toLowerCase())) return false;
    if (c.floorplanIncludes) {
      const cfp = c.floorplanIncludes.toLowerCase().replace(/[\s\-_/]/g, "");
      const nfp = fp.replace(/[\s\-_/]/g, "");
      // Exact after normalize — "35S" must not steal "35QS"
      if (!nfp || nfp !== cfp) return false;
    }
    // Avoid matching "discovery" rule on "discovery lxe" when a more specific exists
    if (c.modelIncludes === "discovery" && md.includes("discovery lxe")) {
      return false;
    }
    // Bare "ventana" must not stamp L9 400 onto Ventana LE
    if (c.modelIncludes === "ventana" && md.includes("ventana le")) {
      return false;
    }
    // Avoid matching bare "allegro red" on "allegro red 340/360"
    if (
      c.modelIncludes === "allegro red" &&
      (md.includes("allegro red 340") ||
        md.includes("allegro red 360") ||
        md.includes("allegro red340") ||
        md.includes("allegro red360"))
    ) {
      return false;
    }
    // Avoid matching bare "reatta" on "reatta xl" if needed later
    if (c.modelIncludes === "reatta" && md.includes("reatta xl")) {
      return false;
    }
    // Vision diesel trim is a different product
    if (
      c.modelIncludes === "vision" &&
      (md.includes("vision xl") || md.includes("diesel"))
    ) {
      return false;
    }
    // Bare "altitude" is E-450 Class C — not FS550 / FS600D Super C
    if (
      c.modelIncludes === "altitude" &&
      (md.includes("fs550") || md.includes("fs600"))
    ) {
      return false;
    }
    // Bare "frontier" must not stamp GTX
    if (c.modelIncludes === "frontier" && md.includes("frontier gtx")) {
      return false;
    }
    // Bare "bounder" must not stamp Bounder Classic
    if (c.modelIncludes === "bounder" && md.includes("bounder classic")) {
      return false;
    }
    // Bare "pace arrow" must not stamp Pace Arrow LXE
    if (c.modelIncludes === "pace arrow" && md.includes("pace arrow lxe")) {
      return false;
    }
    // Bare "discovery" must not stamp Discovery LXE
    if (c.modelIncludes === "discovery" && md.includes("discovery lxe")) {
      return false;
    }
    // Bare "flair" must not stamp Flair LXE
    if (c.modelIncludes === "flair" && md.includes("flair lxe")) {
      return false;
    }
    return true;
  }).sort((a, b) => {
    const af = a.floorplanIncludes ? 1 : 0;
    const bf = b.floorplanIncludes ? 1 : 0;
    if (bf !== af) return bf - af;
    return b.modelIncludes.length - a.modelIncludes.length;
  });

  return hits[0] ?? null;
}

/** True when Live Grok engine text conflicts with a brochure pin. */
export function powertrainConflictsWithPin(
  pin: PowertrainCorrection,
  engine: string | null | undefined,
  horsepower?: number | null,
): boolean {
  if (!engine) return false;
  const live = engine.toLowerCase();
  const pinned = pin.engine.toLowerCase();
  const pinIsMid =
    MID_DIESEL_RE.test(pinned) && !/isl|l9|x15|x12/.test(pinned);
  const liveIsFlagship =
    FLAGSHIP_ENGINE_RE.test(live) ||
    (horsepower != null &&
      pin.horsepower <= 380 &&
      horsepower >= 450);
  if (pinIsMid && liveIsFlagship) return true;
  if (
    /cummins|diesel|isb|b6/.test(pinned) &&
    GAS_V10_RE.test(live) &&
    !/cummins|isb|b6|l9|isl/.test(live)
  ) {
    return true;
  }
  if (
    pin.fuelType === "Gas" &&
    /cummins|diesel|isb|l9|isl/.test(live)
  ) {
    return true;
  }
  return false;
}

/**
 * Rewrite overview / feature chips that still name the wrong powertrain.
 * Keeps market/lifestyle language; strips sibling-engine claims.
 */
export function sanitizeNarrativeForPin(
  pin: PowertrainCorrection,
  text: string | null | undefined,
): string | null {
  if (!text) return text ?? null;
  let t = text;
  const eng = pin.engine;
  const hp = pin.horsepower;
  const tq = pin.torqueLbFt;

  // Replace common wrong powertrains with the pin label
  t = t.replace(
    /Cummins\s+ISL(?:\s*8\.?9L?)?(?:\s+\d+\s*HP)?(?:\s*\/\s*[\d,]+\s*lb-?ft)?/gi,
    eng,
  );
  t = t.replace(
    /Cummins\s+L9(?:\s+\d+\s*HP)?(?:\s*\/\s*[\d,]+\s*lb-?ft)?/gi,
    eng,
  );
  t = t.replace(
    /Ford\s+Triton\s+V10(?:\s*6\.8L)?(?:\s*\([^)]*\))?/gi,
    eng,
  );
  t = t.replace(/Ford\s+F-?53(?:\s+chassis)?/gi, pin.chassis || "chassis");
  if (hp > 0) {
    t = t.replace(/\b450\s*HP\b/gi, `${hp} HP`);
    t = t.replace(/\b320\s*HP\b/gi, `${hp} HP`);
  }
  if (tq && tq > 0) {
    t = t.replace(/\b1[,.]?250\s*lb-?ft\b/gi, `${tq.toLocaleString()} lb-ft`);
    t = t.replace(/\b832\s*lb-?ft\b/gi, `${tq.toLocaleString()} lb-ft`);
  }

  // Drop "early gas Red / gas F53" myths when pin is diesel RED
  if (pin.fuelType === "Diesel" || /cummins|isb|b6/i.test(pin.engine)) {
    t = t.replace(/\bearly\s+years?\s+gas\s+F-?53[^.]*\./gi, "");
    t = t.replace(/\bearly\s+gas\s+Red\b/gi, "diesel Allegro RED");
    t = t.replace(/\bgas\s+F-?53[^.]*\./gi, "");
    t = t.replace(/\b\(gas years\)/gi, "");
  }

  return t.replace(/\s{2,}/g, " ").trim() || null;
}

export function sanitizeFeaturesForPin(
  pin: PowertrainCorrection,
  features: string[] | null | undefined,
): string[] {
  if (!features?.length) return [];
  return features
    .map((f) => sanitizeNarrativeForPin(pin, f) || "")
    .filter(Boolean)
    .filter((f) => {
      // Drop chips that still scream wrong flagship after sanitize
      if (powertrainConflictsWithPin(pin, f)) return false;
      return true;
    })
    .slice(0, 8);
}
