/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRouteRouteImport } from './routes/api/route'
import { Route as ApiGeocodeRouteImport } from './routes/api/geocode'
import { Route as ApiLendersRouteImport } from './routes/api/lenders'
import { Route as ApiOsrmRouteImport } from './routes/api/osrm'
import { Route as ApiRvgrokRouteImport } from './routes/api/rvgrok'
import { Route as ApiMarketcheckSearchRouteImport } from './routes/api/marketcheck.search'
import { Route as ApiNhtsaRecallsRouteImport } from './routes/api/nhtsa.recalls'
import { Route as ApiNhtsaVinRouteImport } from './routes/api/nhtsa.vin'
import { Route as ApiRvfaxCatalogResearchRouteImport } from './routes/api/rvfax.catalog-research'
import { Route as ApiRvfaxCompareRouteImport } from './routes/api/rvfax.compare'
import { Route as ApiRvfaxDossierRouteImport } from './routes/api/rvfax.dossier'
import { Route as ApiRvgrokTokenRouteImport } from './routes/api/rvgrok.token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRouteRoute = ApiRouteRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeocodeRoute = ApiGeocodeRouteImport.update({
  id: '/geocode',
  path: '/geocode',
  getParentRoute: () => ApiRouteRoute,
} as any)
const ApiLendersRoute = ApiLendersRouteImport.update({
  id: '/lenders',
  path: '/lenders',
  getParentRoute: () => ApiRouteRoute,
} as any)
const ApiOsrmRoute = ApiOsrmRouteImport.update({
  id: '/osrm',
  path: '/osrm',
  getParentRoute: () => ApiRouteRoute,
} as any)
const ApiRvgrokRoute = ApiRvgrokRouteImport.update({
  id: '/rvgrok',
  path: '/rvgrok',
  getParentRoute: () => ApiRouteRoute,
} as any)
const ApiMarketcheckSearchRoute = ApiMarketcheckSearchRouteImport.update({
  id: '/marketcheck/search',
  path: '/marketcheck/search',
  getParentRoute: () => ApiRouteRoute,
} as any)
const ApiNhtsaRecallsRoute = ApiNhtsaRecallsRouteImport.update({
  id: '/nhtsa/recalls',
  path: '/nhtsa/recalls',
  getParentRoute: () => ApiRouteRoute,
} as any)
const ApiNhtsaVinRoute = ApiNhtsaVinRouteImport.update({
  id: '/nhtsa/vin',
  path: '/nhtsa/vin',
  getParentRoute: () => ApiRouteRoute,
} as any)
const ApiRvfaxCatalogResearchRoute = ApiRvfaxCatalogResearchRouteImport.update({
  id: '/rvfax/catalog-research',
  path: '/rvfax/catalog-research',
  getParentRoute: () => ApiRouteRoute,
} as any)
const ApiRvfaxCompareRoute = ApiRvfaxCompareRouteImport.update({
  id: '/rvfax/compare',
  path: '/rvfax/compare',
  getParentRoute: () => ApiRouteRoute,
} as any)
const ApiRvfaxDossierRoute = ApiRvfaxDossierRouteImport.update({
  id: '/rvfax/dossier',
  path: '/rvfax/dossier',
  getParentRoute: () => ApiRouteRoute,
} as any)
const ApiRvgrokTokenRoute = ApiRvgrokTokenRouteImport.update({
  id: '/token',
  path: '/token',
  getParentRoute: () => ApiRvgrokRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api': typeof ApiRouteRouteWithChildren
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/lenders': typeof ApiLendersRoute
  '/api/osrm': typeof ApiOsrmRoute
  '/api/rvgrok': typeof ApiRvgrokRouteWithChildren
  '/api/marketcheck/search': typeof ApiMarketcheckSearchRoute
  '/api/nhtsa/recalls': typeof ApiNhtsaRecallsRoute
  '/api/nhtsa/vin': typeof ApiNhtsaVinRoute
  '/api/rvfax/catalog-research': typeof ApiRvfaxCatalogResearchRoute
  '/api/rvfax/compare': typeof ApiRvfaxCompareRoute
  '/api/rvfax/dossier': typeof ApiRvfaxDossierRoute
  '/api/rvgrok/token': typeof ApiRvgrokTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api': typeof ApiRouteRouteWithChildren
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/lenders': typeof ApiLendersRoute
  '/api/osrm': typeof ApiOsrmRoute
  '/api/rvgrok': typeof ApiRvgrokRouteWithChildren
  '/api/marketcheck/search': typeof ApiMarketcheckSearchRoute
  '/api/nhtsa/recalls': typeof ApiNhtsaRecallsRoute
  '/api/nhtsa/vin': typeof ApiNhtsaVinRoute
  '/api/rvfax/catalog-research': typeof ApiRvfaxCatalogResearchRoute
  '/api/rvfax/compare': typeof ApiRvfaxCompareRoute
  '/api/rvfax/dossier': typeof ApiRvfaxDossierRoute
  '/api/rvgrok/token': typeof ApiRvgrokTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api': typeof ApiRouteRouteWithChildren
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/lenders': typeof ApiLendersRoute
  '/api/osrm': typeof ApiOsrmRoute
  '/api/rvgrok': typeof ApiRvgrokRouteWithChildren
  '/api/marketcheck/search': typeof ApiMarketcheckSearchRoute
  '/api/nhtsa/recalls': typeof ApiNhtsaRecallsRoute
  '/api/nhtsa/vin': typeof ApiNhtsaVinRoute
  '/api/rvfax/catalog-research': typeof ApiRvfaxCatalogResearchRoute
  '/api/rvfax/compare': typeof ApiRvfaxCompareRoute
  '/api/rvfax/dossier': typeof ApiRvfaxDossierRoute
  '/api/rvgrok/token': typeof ApiRvgrokTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api'
    | '/api/geocode'
    | '/api/lenders'
    | '/api/osrm'
    | '/api/rvgrok'
    | '/api/marketcheck/search'
    | '/api/nhtsa/recalls'
    | '/api/nhtsa/vin'
    | '/api/rvfax/catalog-research'
    | '/api/rvfax/compare'
    | '/api/rvfax/dossier'
    | '/api/rvgrok/token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api'
    | '/api/geocode'
    | '/api/lenders'
    | '/api/osrm'
    | '/api/rvgrok'
    | '/api/marketcheck/search'
    | '/api/nhtsa/recalls'
    | '/api/nhtsa/vin'
    | '/api/rvfax/catalog-research'
    | '/api/rvfax/compare'
    | '/api/rvfax/dossier'
    | '/api/rvgrok/token'
  id:
    | '__root__'
    | '/'
    | '/api'
    | '/api/geocode'
    | '/api/lenders'
    | '/api/osrm'
    | '/api/rvgrok'
    | '/api/marketcheck/search'
    | '/api/nhtsa/recalls'
    | '/api/nhtsa/vin'
    | '/api/rvfax/catalog-research'
    | '/api/rvfax/compare'
    | '/api/rvfax/dossier'
    | '/api/rvgrok/token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRouteRoute: typeof ApiRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geocode': {
      id: '/api/geocode'
      path: '/geocode'
      fullPath: '/api/geocode'
      preLoaderRoute: typeof ApiGeocodeRouteImport
      parentRoute: typeof ApiRouteRoute
    }
    '/api/lenders': {
      id: '/api/lenders'
      path: '/lenders'
      fullPath: '/api/lenders'
      preLoaderRoute: typeof ApiLendersRouteImport
      parentRoute: typeof ApiRouteRoute
    }
    '/api/osrm': {
      id: '/api/osrm'
      path: '/osrm'
      fullPath: '/api/osrm'
      preLoaderRoute: typeof ApiOsrmRouteImport
      parentRoute: typeof ApiRouteRoute
    }
    '/api/rvgrok': {
      id: '/api/rvgrok'
      path: '/rvgrok'
      fullPath: '/api/rvgrok'
      preLoaderRoute: typeof ApiRvgrokRouteImport
      parentRoute: typeof ApiRouteRoute
    }
    '/api/marketcheck/search': {
      id: '/api/marketcheck/search'
      path: '/marketcheck/search'
      fullPath: '/api/marketcheck/search'
      preLoaderRoute: typeof ApiMarketcheckSearchRouteImport
      parentRoute: typeof ApiRouteRoute
    }
    '/api/nhtsa/recalls': {
      id: '/api/nhtsa/recalls'
      path: '/nhtsa/recalls'
      fullPath: '/api/nhtsa/recalls'
      preLoaderRoute: typeof ApiNhtsaRecallsRouteImport
      parentRoute: typeof ApiRouteRoute
    }
    '/api/nhtsa/vin': {
      id: '/api/nhtsa/vin'
      path: '/nhtsa/vin'
      fullPath: '/api/nhtsa/vin'
      preLoaderRoute: typeof ApiNhtsaVinRouteImport
      parentRoute: typeof ApiRouteRoute
    }
    '/api/rvfax/catalog-research': {
      id: '/api/rvfax/catalog-research'
      path: '/rvfax/catalog-research'
      fullPath: '/api/rvfax/catalog-research'
      preLoaderRoute: typeof ApiRvfaxCatalogResearchRouteImport
      parentRoute: typeof ApiRouteRoute
    }
    '/api/rvfax/compare': {
      id: '/api/rvfax/compare'
      path: '/rvfax/compare'
      fullPath: '/api/rvfax/compare'
      preLoaderRoute: typeof ApiRvfaxCompareRouteImport
      parentRoute: typeof ApiRouteRoute
    }
    '/api/rvfax/dossier': {
      id: '/api/rvfax/dossier'
      path: '/rvfax/dossier'
      fullPath: '/api/rvfax/dossier'
      preLoaderRoute: typeof ApiRvfaxDossierRouteImport
      parentRoute: typeof ApiRouteRoute
    }
    '/api/rvgrok/token': {
      id: '/api/rvgrok/token'
      path: '/token'
      fullPath: '/api/rvgrok/token'
      preLoaderRoute: typeof ApiRvgrokTokenRouteImport
      parentRoute: typeof ApiRvgrokRoute
    }
  }
}

interface ApiRvgrokRouteChildren {
  ApiRvgrokTokenRoute: typeof ApiRvgrokTokenRoute
}

const ApiRvgrokRouteChildren: ApiRvgrokRouteChildren = {
  ApiRvgrokTokenRoute: ApiRvgrokTokenRoute,
}

const ApiRvgrokRouteWithChildren = ApiRvgrokRoute._addFileChildren(
  ApiRvgrokRouteChildren,
)

interface ApiRouteRouteChildren {
  ApiGeocodeRoute: typeof ApiGeocodeRoute
  ApiLendersRoute: typeof ApiLendersRoute
  ApiOsrmRoute: typeof ApiOsrmRoute
  ApiRvgrokRoute: typeof ApiRvgrokRouteWithChildren
  ApiMarketcheckSearchRoute: typeof ApiMarketcheckSearchRoute
  ApiNhtsaRecallsRoute: typeof ApiNhtsaRecallsRoute
  ApiNhtsaVinRoute: typeof ApiNhtsaVinRoute
  ApiRvfaxCatalogResearchRoute: typeof ApiRvfaxCatalogResearchRoute
  ApiRvfaxCompareRoute: typeof ApiRvfaxCompareRoute
  ApiRvfaxDossierRoute: typeof ApiRvfaxDossierRoute
}

const ApiRouteRouteChildren: ApiRouteRouteChildren = {
  ApiGeocodeRoute: ApiGeocodeRoute,
  ApiLendersRoute: ApiLendersRoute,
  ApiOsrmRoute: ApiOsrmRoute,
  ApiRvgrokRoute: ApiRvgrokRouteWithChildren,
  ApiMarketcheckSearchRoute: ApiMarketcheckSearchRoute,
  ApiNhtsaRecallsRoute: ApiNhtsaRecallsRoute,
  ApiNhtsaVinRoute: ApiNhtsaVinRoute,
  ApiRvfaxCatalogResearchRoute: ApiRvfaxCatalogResearchRoute,
  ApiRvfaxCompareRoute: ApiRvfaxCompareRoute,
  ApiRvfaxDossierRoute: ApiRvfaxDossierRoute,
}

const ApiRouteRouteWithChildren = ApiRouteRoute._addFileChildren(
  ApiRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRouteRoute: ApiRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
